### ISSUE TITLE
Autofill sample rate and sample format when .wav input is selected

### ISSUE THREAD

**Issue by shuyuan-liu** [SatDump/SatDump#10]
As .wav files carry the sample rate and sample format information, it would be convenient if SatDump could extract them and fill them in the respective boxes automatically.

**Comment by Aang23** [comment]
That's a good idea. I would probably call this right after file selection.


> In my opinion, i16 wav files are fine to just treat as i16 raw files. The wav header is 44 bytes long, which is an integer multiple of i16 x 2 channels (4 bytes), and after that there is just raw i16 data. The header will simply be interpreted as a short burst of noise at the beginning and should be insignificant. u8 wav files can be treated similarly.

It's the same conclusion I came onto a while ago. It makes no difference whatsoever and allows treating "raw" and wav files in the same way (except for u8)... The header is so short it really doesn't matter, 44 bytes when you're working with files of at least a few hundred MBs and often in the order of 10+ GiB is nothing.
