### ISSUE TITLE
GEO Projection configurations and products missing

### ISSUE THREAD

**Issue by ZbychuButItWasTaken** [SatDump/SatDump#129]
Yes they are gonna be added.

**Comment by Aang23** [comment]
Todo : 
- [ ] GOES-16
- [ ] GOES-17
- [ ] ELEKTRO-L 2
- [ ] ELEKTRO-L 3
- [ ] Himawari-8
- [ ] GOES-13 (EWS-G1)

**Comment by Aang23** [comment]
GOES-16 (Full Disk and CONUS), valid on GRB / HRIT
![test_goes_idk](https://user-images.githubusercontent.com/23421917/190859372-cc10aaf0-af0f-4b49-9169-5e6359695224.jpg)
![test_goes_idk](https://user-images.githubusercontent.com/23421917/190859292-cf1c756c-568a-4f73-aa5b-6601477b377c.jpg

The overlay can be applied using `./apply_mapoverlay source_image.png settings.json output.png` build when -DBUILD_TOOLS=ON is set. It's only as products.cbor are not produced yet, and the tool I use to tune them.

[goes16_projs.zip](https://github.com/altillimity/SatDump/files/9591785/goes16_projs.zip)
)

**Comment by Aang23** [comment]
ELEKTRO-L 3 (LRIT / HRIT)
I only had older data on hand from before it was officially operational. It's not perfectly aligned, might be due to that.
![test_goes_idk](https://user-images.githubusercontent.com/23421917/190860939-f0507bdc-d8ec-4a64-9425-3d90ddd47d79.jpg)
[elektrol3.zip](https://github.com/altillimity/SatDump/files/9591853/elektrol3.zip)

**Comment by Aang23** [comment]
GK-2A (LRIT / HRIT)
![test_goes_idk](https://user-images.githubusercontent.com/23421917/190861551-546ece65-c4de-4079-a69a-b9c37bae4cd6.jpg)
[gk2a.zip](https://github.com/altillimity/SatDump/files/9591872/gk2a.zip)

**Comment by Aang23** [comment]
GOES-17 (HRIT / GRB) FullDisk (no ""CONUS"" on Hand right now)
![test_goes_idk](https://user-images.githubusercontent.com/23421917/190862108-739eb476-1f4b-473e-8210-ebfe81b891a1.png)
[goes17_fulldisk.zip](https://github.com/altillimity/SatDump/files/9591898/goes17_fulldisk.zip)

**Comment by Aang23** [comment]
Closing this, as xRIT now generated projection configs. Some config samples to import other GEO images should be added on the website though.
