### ISSUE TITLE
suggestion - adding false color heatmaps to thermal images

### ISSUE THREAD

**Issue by RAD750** [SatDump/SatDump#143]
Hello,
The new V1.0 beta is **extremely** good news, now I no longer have to rely on separate software (SatDump+LeanHRPT) to decode my HRPT receptions to the fullest extent.

One thing I am missing, is a colormap option, especially for things like thermal channels or HIRS. I now use a small Python script that uses OpenCV to add the colormap.

I wonder if this could this be added in a future version?

Thanks again for this excellent and very useful software.

**Comment by ZbychuButItWasTaken** [comment]
Yes that is possible and planned!
