### ISSUE TITLE
Does the decimation option work in the CLI version?

### ISSUE THREAD

**Issue by sergsero** [SatDump/SatDump#250]
Hello,

Can I assume that the `decimation` function also works in the CLI version of the program?
And also that it works in GUI and in CLI the same way?

In the logs I get messages about enabling decimation  with different values for the GUI and for the CLI.
Although it is not documented, in the CLI to run the program I use the option `--decimation 3`.
``
#!/bin/bash
./satdump live fengyun_svissr /home/sergsero/data --source airspy --samplerate 6e6 --frequency 1687.5e6 --general_gain 15 gain_type 0 --lna_agc --decimation 3
``

The expected value is displayed in the GUI: `Samplerate 2000000`

![20230211_decimation_gui](https://user-images.githubusercontent.com/4005442/218261824-3d15add9-b5ac-49af-ba25-99da3fcfd6cc.png)

But in the CLI, despite the line decimation 3, another value:  `Samplerate : 2400000.000000` and `Dec factor : 2.500000`

![20230211_decimation_cli_err](https://user-images.githubusercontent.com/4005442/218261863-07dc59d2-3613-45af-b961-d1e6db42d831.png)

Or am I wrong and misunderstand the records in the log?

Sincerely,
sergsero

**Comment by Aang23** [comment]
If in live mode, decimation is automatically decided and done by SatDump's demodulator. Hence, adding a custom --decimation is live mode does not make a lot of sense at all.

It would make sense to have in CLI recording however.
