### ISSUE TITLE
Frequency axis: Display of actual frequency instead of baseband frequency

### ISSUE THREAD

**Issue by eswnl** [SatDump/SatDump#252]
**What would you want to be added to satdump?**
On the frequency axis, cursor displays baseband frequency instead of actual frequency. Is it worth changing the frequency axis to display actual RF frequency?

![image](https://user-images.githubusercontent.com/59115800/218298460-d2a85a26-a713-45d0-b3ba-cc4d8f8cd9f7.png)

**Comment by Aang23** [comment]
I agree. It's something we've been thinking about more and more. The main issue is, not too sure how to go about it UI-wise, to now have it interfere with the rest too much etc.

A VFO system will be coming for those narrower signals, in a similar style to other SDR apps.

**Comment by ZbychuButItWasTaken** [comment]
Well what we have now is a placeholder while the VFOs are implemented. No changes will be made to the UI until VFOs are functional the the UI for that is implemented (because it will require a solid rewrite anyway)
