### ISSUE TITLE
Satdump keeps disabling bias-tee

### ISSUE THREAD

**Issue by rodavrow** [SatDump/SatDump#261]
Hi! Thanks for the amazing software 👍 
I'm having an issue when connecting to my remote RTL-SDR, I have enabled Bias-Tee when starting rtl_tcp but when I connect to it, SatDump tells it to disable. There isn't a tick box or option anywhere to enable it I can see. Any idea where I'm going wrong?

Thanks!

**Comment by Aang23** [comment]
Fixed.
