### ISSUE TITLE
Add support for BladeRF?

### ISSUE THREAD

**Issue by jamesmac10** [SatDump/SatDump#266]
Hi there,

There seems to be quite a few people out there with blades that would fit in your demographic. Any plans to release support? I personally have the bladerf 2.0 micro xa4 and its a great tool.

Thanks,

Jamesmac10

**Comment by AlexandreRouma** [comment]
It's already supported

**Comment by pluggerlockett** [comment]
Can confirm, I've got that exact bladeRF and it works in SatDump. You have to install libbladerf-dev (I think that's the package name) to get it to work though. For some reason that's not included in the Install instructions.

**Comment by jamesmac10** [comment]
Ok, I will install the package and give it a shot. Thank you!

**Comment by Aang23** [comment]
Yes, indeed BladeRF is already supported, You will need to do what @pluggerlockett said to get it working.
