### ISSUE TITLE
error about RtAudio Library 

### ISSUE THREAD

**Issue by wer596** [SatDump/SatDump#268]
I'm trying deploy the system on ubuntu. When I use the cmake  command，I meet these errors:
LimeSDR Library could not be found! Not building.
RtAudio Library could not be found! Not building.   
RtAudio Library could not be found! Not building.

Does the LimeSDR Library mean gr-limesdr?
And after I install the RtAudio, the error became:
Building with RtAudio sink
RtAudio Library could not be found! Not building.
So, what is the second RtAudio Library mean?

**Comment by Aang23** [comment]
LimeSDR Library means LimeSuite. RtAudio is optional, this is not an error.
