### ISSUE TITLE
Unable to start satdump

### ISSUE THREAD

**Issue by DroidKali** [SatDump/SatDump#275]
**Description of the issue**
Unable to start satdump, double-click the satdump-ui.exe but nothing happen.
Run the satdump.exe in cmd.exe as the same result.
**Hardware (SDR/PC/OS)**
RTL-SDR Blog V3 dongle
amd Athlon(tm) ⅱ X4 631
Windows 10 Enterprise LTSC 2021
**Version (Eg, 1.0.0, CI Build #171)**
1.0.3
**Logs after the cras (satdump.logs)**
Not create the log
**Other info (Eg, Screenshots) / Files useful for debugging (CADU, etc)**
![](https://files.catbox.moe/oj4w3z.png)

**Comment by JVital2013** [comment]
Do you have Microsoft Visual C++ Redistributable installed? You can get it from https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Aang23** [comment]
I'd guess this is the most likely issue here, probably a missing C++ Runtime.

**Comment by cfd238** [comment]
I am having same issue.

**Comment by cfd238** [comment]
I am having same issue.  Have updated C++ runtime,  issue persists.
Windows 10 Pro (unlicensed) - 10.0.19045 Build 19045
Old HP 2000 Notebook AMD e-300 APU /radeon HD 6310 graphics

**Comment by Aang23** [comment]
Are you launching satdump-ui.exe?

**Comment by DroidKali** [comment]
> Are you launching satdump-ui.exe?
> 
> Edit : Can you try the latest CI build just in case?

I have tryed the latest CI build and it has been fixed this issue.
Thanks for your help!
![](https://files.catbox.moe/397tyn.png)
