### ISSUE TITLE
Date error in the console log (GUI)

### ISSUE THREAD

**Issue by sergsero** [SatDump/SatDump#277]
**Description of the issue**
Earlier it was noted that the program incorrectly processes the system date and time if they differ from UTC and are issued in a non-Latin variant.
I changed a system time and date to UTC and the system language to English.
Now the time in UTC is correct. But the satdump-ui's console log in all the latest git versions is exactly one month late. Today, 07.05.2023 is indicated in the program as 07.04.2023.

![Screenshot from 2023-05-07 09-32-15_aa](https://user-images.githubusercontent.com/4005442/236672718-80e0d39d-bbb6-46e1-8446-5803383608cc.png)

At the same time, the folder name is formed correctly by the program.
![Screenshot from 2023-05-07 09-51-53_aa1](https://user-images.githubusercontent.com/4005442/236672723-64086e39-23a6-49fc-b55c-9ffb70202fd5.png)

Can this be fixed?

**Hardware (SDR/PC/OS)**
Linux 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Aang23** [comment]
Fixed
