### ISSUE TITLE
Install errors MacOS

### ISSUE THREAD

**Issue by VincentVolmer** [SatDump/SatDump#279]
Hello,

Install stops at 32%. Mac OS Catalina 10.15.7 - XCode 12.4

A lot of warnings generated.
[ 32%] Linking CXX shared library ../libsatdump_core.dylib
ld: library not found for -lvolk
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libsatdump_core.dylib] Error 1
make[1]: *** [src-core/CMakeFiles/satdump_core.dir/all] Error 2
make: *** [all] Error 2

What can I do next? Thanks for any help!
Vy73 Vincent PE2V

**Comment by Aang23** [comment]
How did you install volk?

**Comment by VincentVolmer** [comment]
Hello,
Thank you for your answer. I followed all steps at the main page. I installed volk this way:

# macOS: Install dependencies
brew install cmake volk libpng glew glfw nng pkg-config llvm libomp luajit

**Comment by VincentVolmer** [comment]
Hello,
Thank you for your answer. I followed all steps at the main page. I installed volk this way:

# macOS: Install dependencies
brew install cmake volk libpng glew glfw nng pkg-config llvm libomp luajit

**Comment by VincentVolmer** [comment]
Tried it again and I see: Error: volk: SHA256 mismatch so I'll try to install with Port (if present)

**Comment by VincentVolmer** [comment]
Installed volk

When I run the line: 
`cmake -DCMAKE_BUILD_TYPE=Release ..`

I see this about volk:
```
-- Checking for module 'volk'
--   Found volk, version 2.5
-- Performing Test VOLK_HAS_ALLOC
-- Performing Test VOLK_HAS_ALLOC - Failed
-- VOLK does not have volk_alloc.hh, including volk_includes
```

When running build (I have to do this first, because nproc is not a command om Mac):
`alias nproc="sysctl -n hw.logicalcpu"`

```
build % make -j`nproc` 
```
I still see this:
```
[  1%] Linking CXX shared library ../libsatdump_core.dylib
ld: library not found for -lvolk
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libsatdump_core.dylib] Error 1
make[1]: *** [src-core/CMakeFiles/satdump_core.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by Aang23** [comment]
Where is the .dylib installed? It sounds like Volk isn't in a standard directory so SatDump isn't able to find it.

**Comment by VincentVolmer** [comment]
I don't know how to find... could you please help? Secondly I can try to install volk again with brew but it has still the SHA256 mismatch error...

**Comment by AlexandreRouma** [comment]
try running `brew update` and then `brew cleanup`. Then try installing volk with it again.

**Comment by VincentVolmer** [comment]
Thank... did that but still the "Error: volk: SHA256 mismatch"... so not possible to install volk with brew for now. So I reported this to https://github.com/google/cpu_features.git

**Comment by Aang23** [comment]
Perhaps build and install Volk manually?

**Comment by VincentVolmer** [comment]
Ok, install volk is OK now. But an other error at 95% and install stops...:

[ 95%] Built target bladerf_sdr_support
make: *** [all] Error 2

**Comment by Aang23** [comment]
Did you clean it all up from scratch? Can you show the full logs? here I can't see the error.

**Comment by VincentVolmer** [comment]
Hello,
I just started from "# Finally, SatDump", and before that I did 'mv satdump satdumptemp'.

**Comment by VincentVolmer** [comment]
I started from scratch but it ended the same way at 95% ... maybe it is not running on my MacOS Catalina 10.15.7

**Comment by VincentVolmer** [comment]
Good morning, I'll give it a try today..... first some brew updates .... :)

**Comment by JVital2013** [comment]
That's the best part - brew is no longer required!

**Comment by VincentVolmer** [comment]
> That's the best part - brew is no longer required!

Okay.... after brew is ready (still updating) I can start at this point?: 
# Finally, SatDump 
git clone https://github.com/altillimity/satdump.git
etc....

**Comment by JVital2013** [comment]
What I meant is compiling is no longer necessary - just download the dmg from https://github.com/SatDump/SatDump/releases/tag/nightly

**Comment by VincentVolmer** [comment]
Aah ohw... thats great. Goin' to try now!

**Comment by VincentVolmer** [comment]
That was easy! It's running.... and now I need to find out how it is working.... Thank you for your help!!

**Comment by JVital2013** [comment]
Heh, that's the trick to SatDump. I'm still learning about all it has to offer :). 

Feel free to close this issue if you feel the pre-compiled build resolves your problem!
