### ISSUE TITLE
Automatically archive CADU/Frames to a specific folder

### ISSUE THREAD

**Issue by RAD750** [SatDump/SatDump#284]
**What would you want to be added to satdump?**
(As discussed with Aang on the matrix)

An option should be added to automatically save the CADU/Frames file output by the offline process, to a specific directory with a specific filename pattern.

**Describe the feature you'd like to have**
After setting up the "CADU/Frames archive directory" from the settings and running an offline decode, the CADU/Frame file produced should be renamed according to a convention (something like `YYYYMMDDHHMMSS_Satellite.cadu` and copied to the specified directory.

**Describe alternatives you've considered**
Manual archival by copying and renaming the file (tedious)

**Additional context**
In "Output directories" add an option: CADU/Frames archive directory (with checkbox)
Optionally also add a personalized filename pattern textbox.

**Comment by Fabrimat** [comment]
That would be an important feature to be added, i'm surpised it's still open
