### ISSUE TITLE
Error & status messages overlap with other UI elements

### ISSUE THREAD

**Issue by RAD750** [SatDump/SatDump#286]
**Description of the issue**

Error and status messages overlap other stuff, like progress bars and tables, because they are not at the foreground.

![immagine](https://github.com/SatDump/SatDump/assets/12469744/748f222c-ca1d-4532-9294-42abf1e2f16b)

**Hardware (SDR/PC/OS)**
Thinkpad X260
Pop!_OS 22.04

**Comment by Aang23** [comment]
I'll admit this is a really weird one....

**Comment by RAD750** [comment]
Alan there is also another issue where this is evident #289 
![immagine](https://github.com/SatDump/SatDump/assets/12469744/6f40d565-87aa-46ed-9add-e448f24a99a7)
