### ISSUE TITLE
Wrongly processing an audio .wav file for APT as baseband causes satdump to stop processing any file

### ISSUE THREAD

**Issue by RAD750** [SatDump/SatDump#289]
**Description of the issue**
Wrongly processing an audio .wav file for APT as baseband causes satdump to stop processing any file until it is restarted

**Hardware (SDR/PC/OS)**
Not hardware specific, but it's an HP Elitebook 820 G2.

OS: Linux Mint 21.1

**Version (Eg, 1.0.0, CI Build #171)**
1.1.0-25fdf148

**Logs after the cras (satdump.logs)**
[satdump.log](https://github.com/SatDump/SatDump/files/11859217/satdump.log)

**Steps to reproduce**
1. Obtain an audio recording of a NOAA APT satellite, such as NOAA 19, from another program such as SDR++ or GQRX.
2. Configure the satdump window as follows
![immagine](https://github.com/SatDump/SatDump/assets/12469744/46be144e-cc98-454c-b9b0-ef19b044b53e)

3. Push start

![immagine](https://github.com/SatDump/SatDump/assets/12469744/15f282b8-d240-49cf-82b3-9413fdc933da)
4. Of course, it will give lots of errors (which is expected)
![immagine](https://github.com/SatDump/SatDump/assets/12469744/3097cb13-71b8-44a8-b92b-156da0399c19)

5. The start button no longer works, even if you change pipeline or reselect the file.

5.

**Comment by MrQbasic** [comment]
![grafik](https://github.com/SatDump/SatDump/assets/77384846/0f1dc15c-efff-4b57-aba9-cfa8ccef0d9f)

I get the same error + this is my processing screen. Also if you switch to other tabs while processing you only see a blank window. Same version / build as you can see in the titlebar of the window.

**Comment by RAD750** [comment]
@MrQbasic yours is not related to the bug report, and I can see a composite. Try using the mouse to enlarge the product viewer.if you still can't, open another bug report

**Comment by RAD750** [comment]
The same happens if you press abort

**Comment by Aang23** [comment]
Well I can reproduce, what a weird one.
