### ISSUE TITLE
Viewer sometimes showing the option to overlay map / project

### ISSUE THREAD

**Issue by MrQbasic** [SatDump/SatDump#290]
**Description of the issue**
For older, already decoded data everything works fine but if i try to decode a noaa apt singal now i get errors during the decoding. The images come out fine but i get no telemetry.

**Hardware (SDR/PC/OS)**
SDR: RTL-SDR (does not really matter as i used an other program to decode)
PC: Dell Latitude xt3
OS: Archlinux

**Version (Eg, 1.0.0, CI Build #171)**
v1.1.0-25fdf148

**Logs after the cras (satdump.logs)**
[satdump.log](https://github.com/SatDump/SatDump/files/11860155/satdump.log)

**Other info (Eg, Screenshots) / Files useful for debugging (CADU, etc)**
![grafik](https://github.com/SatDump/SatDump/assets/77384846/6ccfde73-113d-4d39-8c96-8cb16c0fdd6a)
![grafik](https://github.com/SatDump/SatDump/assets/77384846/701ed66c-c0f3-408b-b6b8-cfadb0a33bae)

This is while decoding
![grafik](https://github.com/SatDump/SatDump/assets/77384846/452cb1f7-a9bd-4493-83ee-5e954fec6a8a)

This is when it crashes
![grafik](https://github.com/SatDump/SatDump/assets/77384846/56a6beea-5cf0-44f9-996b-07e5de3cceb3)

This is the dataset.json file from a good file left and the new bad file right
![grafik](https://github.com/SatDump/SatDump/assets/77384846/c46b8135-8d2a-4833-9d60-af8f98dd2c1f)

**Comment by Aang23** [comment]
Is this still an issue? Can you upload a file so I can test?

**Comment by Aang23** [comment]
Closing for now, since no feedback and no other reports.
If this is still an issue, I'll re-open.
