### ISSUE TITLE
Don't abort immediately when a composite fails 

### ISSUE THREAD

**Issue by moh53n** [SatDump/SatDump#300]
**What would you want to be added to satdump?**
SatDump will panic and abort when a composite generation fails. However, this might be unnecessary since a poor capture, bad config, or a software bug might trigger the error for a single composite. This prevents the other composites from being generated.

**Describe the feature you'd like to have**
SatDump can simply throw an error or a warning about the failed composite and still try to generate the other composites.

**Comment by Aang23** [comment]
Do you have the logs on hand?
