### ISSUE TITLE
add Frequency to Spectrum/Waterfall window

### ISSUE THREAD

**Issue by db2os** [SatDump/SatDump#315]
Add frequencies to the X-Axis, draw a small red line indicating the frequency we are currently centered. With a larger text windows, showing the frequency

Something like this:
![grafik](https://github.com/SatDump/SatDump/assets/53628992/9a705d84-546a-4d5c-be54-d5f4f3ab197a)

**Comment by db2os** [comment]
Another suggestion for the Spectrum; not only should it include frequency notation, but it should also carry the date & time somewhere.

**Comment by db2os** [comment]
Already in use!  - Thanks :-)
![grafik](https://github.com/SatDump/SatDump/assets/53628992/b7d616bd-3789-44e9-a96b-cc71d4f19917)

**Comment by Aang23** [comment]
Still somewhat basic, could maybe use some improvements later... But it's there!
