### ISSUE TITLE
Hi, is it possible to have a debian package for raspberry? Thanks

### ISSUE THREAD

**Issue by pade1036** [SatDump/SatDump#335]
Hi

**Comment by Aang23** [comment]
It is, but at the moment Github does not offer ARM workers, making it complicated to do cleanly. It will happen when possible, or I put more work into making cross-compilation function (it works fine, but dpkg-sheplib doesn't want to work...).

**Comment by JVital2013** [comment]
Hi @pade1036, we now have a package available for arm64, which will work on all Raspberry Pi's, model 3 and newer - assuming you have the modern 64-bit OS installed. Will this meet your needs?

**Comment by alexmyczko** [comment]
Yes, https://buildd.debian.org/status/package.php?p=satdump

**Comment by JVital2013** [comment]
Good point! With the addition of Debian builds, several more platforms are covered as well, so this issue appears addressed.
