### ISSUE TITLE
Recorder Floating Windows hiding

### ISSUE THREAD

**Issue by PY2PLL** [SatDump/SatDump#336]
**After the build 8c15183 the recorder floating windows hide behind the main screen , barely visible and no way to click them to bring them back to foreground again. To start this behavior on e.g. NOAA APT, with PROCESSING running select tracker drop down menu. To bring them back to foreground is necessary to stop/start PROCESSING.**

**Hardware (SDR/PC/OS) AirSpy Discovery/i5 16G RAM/w10 pro**

**Version (Eg, 1.1.0, CI Build #8206471)**

**Other info (Eg, Screenshots) / Files useful for debugging (CADU, etc)**
![image](https://github.com/SatDump/SatDump/assets/44536158/7475b040-497b-43bc-95cd-26b2174c829c)

**Comment by ZbychuButItWasTaken** [comment]
I have been able to reproduce the issue, working on a fix.
