### ISSUE TITLE
Have a automated healing function like in Meteorgis

### ISSUE THREAD

**Issue by benklerk** [SatDump/SatDump#341]
**What would you want to be added to satdump?**
A clear and concise description of what the idea/problem is.

Is it possible to have a healing function to repair missing data like in meteorgis. I'm sure it will benefit for all satellite images that has some missing data. Using photoshop can be very time consuming and having it automated would be nice   

**Describe the feature you'd like to have**

To have some type of auto healing to fix missing data to images so you don't have black or white lines throughout the image. Using photoshop/gimp healing is time consuming and not everyone has the program. Having it do something similar to meteorgis would be nice and would help a lot of people who use satdump and can be used with other satellites to make nicer looking images.

I don't know how hard it would be to introduce this into satdump, but would make a good alternative solution to heal images faster.

**Comment by Aang23** [comment]
Well, @JVital2013 I think that's done.... :-)
