### ISSUE TITLE
ch10,ch10,ch1 doesn't work on MWHS-2

### ISSUE THREAD

**Issue by RAD750** [SatDump/SatDump#344]
**Description of the issue**
ch10,ch10,ch1 doesn't work on MWHS-2; satdump complains about an Unexpected token.

@Aang23 knows about it :)

![immagine](https://github.com/SatDump/SatDump/assets/12469744/6234ead2-a29c-4354-b333-921abfe7fe74)

**Comment by Aang23** [comment]
Sure helps to have been right there when it happened :-)
