### ISSUE TITLE
RGB-Layer not synchronized

### ISSUE THREAD

**Issue by LEDFlighter** [SatDump/SatDump#367]
**Problem:** The RGB-Layers are sometimes not synchronized.
The resulting image then looks something like this:

![image](https://github.com/SatDump/SatDump/assets/78096516/a99e6e59-657b-46f7-a0a1-8eaca32a8e18)

**Hardware:** RTL-SDR V3 with Microsoft Windows 10 Pro, 64-Bit

**Version:** Latest Nightly-Build, but happened to me earlier already

.cadu-file is attached

[meteor_m2-x_lrpt_CADU.zip](https://github.com/SatDump/SatDump/files/12423660/meteor_m2-x_lrpt_CADU.zip)

**Comment by Aang23** [comment]
Fixed, normally.
