### ISSUE TITLE
new satdump pipeline 

### ISSUE THREAD

**Issue by ramers87** [SatDump/SatDump#408]
Hello 
how i can add new satdump pipeline satellite ?
Thanks

**Comment by Marhmarchi** [comment]
You must create a json file in the pipelines folder, following the same structure as the others.

**Comment by ramers87** [comment]
Hi,
Thank you so much for your help i solved it.

Le lun. 18 sept. 2023, 18:47, Marhmarchi ***@***.***> a
écrit :

**Comment by Marhmarchi** [comment]
You're welcome 🤩

**Comment by ramers87** [comment]
Just one more thing how i can make desktop icon for satdump to lunch it up

Le lun. 18 sept. 2023, 19:08, Marhmarchi ***@***.***> a
écrit :

**Comment by Marhmarchi** [comment]
Depends on your OS (Mac, Linux, Windows..), but when you build the package it creates the shortcut. If you didn't install it system-wide, then look for instructions for your OS, then use the satdump-ui as the executable on the shortcut.

**Comment by ramers87** [comment]
Yes i use ./satdump-ui,but i need icon desktop,i use Debian Linux

Le lun. 18 sept. 2023, 19:28, Marhmarchi ***@***.***> a
écrit :

**Comment by Aang23** [comment]
If you just do `sudo make install` you should get the Desktop icon by default.

Also @ramers87 feel free to join the Matrix group mentioned in the README if you need more help!

**Comment by ramers87** [comment]
Hi,
How to add a new pipeline satellite? ,only way is modify json file?

**Comment by ramers87** [comment]
I didn't know the staeps  to join MATRIX groupe?

**Comment by Crosswalkersam** [comment]
Yes, the only way to get SatDump to support a satelite is to modify or create a new .json file in the pipeline folder.

**Comment by JVital2013** [comment]
@ramers87 To join Matrix, go to https://matrix.to/#/#satdump:altillimity.com.

Is there anything specific we can help you with?

**Comment by JVital2013** [comment]
Since we haven't heard back from you, I'm going to close this issue. If you still need help, feel free to re-open it. Thanks!

**Comment by ramers87** [comment]
Hi
Thank you so much it was helpful.
Regards

Le lun. 30 oct. 2023, 15:28, Jamie Vital ***@***.***> a
écrit :
