### ISSUE TITLE
Satdump crash with Windows 11 systems how to fix!

### ISSUE THREAD

**Issue by IZ5RZR** [SatDump/SatDump#413]
In this video I show you what the problem is with the new satdump builds and how to solve it. the crash is caused by errors in downloading the 2line elements from celestrack, which has changed the download locations, therefore when the program tries to download the tles of some staellites it does not find them and reports error codes in the Satdump.tles text, therefore the the next time the program is started it fails to process the satdump.tles file and crashes.
The only way to solve it is to edit the Satdump.tles file and remove all the error codes, there are several, save and then it works!
I have make a video tutorial [https://youtu.be/U4HCo-WmYt4?si=hqDotg8_AnubrpS2](url)

IZ5RZR Max

**Comment by Aang23** [comment]
Which build are you using exactly?

**Comment by IZ5RZR** [comment]
HI

   all last builds from 28 jun 2023
   Da "Aang23" ***@***.***
   A "SatDump/SatDump" ***@***.***
   Cc "Max" ***@***.***,"Author" ***@***.***
   Data Wed, 20 Sep 2023 02:45:23 -0700
   Oggetto Re: [SatDump/SatDump] Satdump crash with Windows 11 systems how to fix! (Issue #413)

   Which build are you using exactly?

**Comment by IZ5RZR** [comment]
> 28 jun is old. Can you try newer?

All recently buils are affected

**Comment by IZ5RZR** [comment]
> Ok, can you send the bugger satdump_tles.txt?

Have you seen video?
here is satdump.tles , look all <HEAD><TITLE>Connection timed out</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black">
<FONT FACE="Helvetica,Arial"><B>
-----------------------------------------------------------------
METOP-A                 
1 29499U 06044A   23263.43761744  .00002357  00000+0  31089-3 0  9999
2 29499  98.3907 326.5172 0192964   3.4631   6.8172 14.68981089881011
METOP-B                 
1 38771U 12049A   23263.39222104  .00000240  00000+0  12941-3 0  9996
2 38771  98.6691 321.1331 0001366  98.9864 271.9342 14.21516599571072
METOP-C                 
1 43689U 18087A   23263.42708251  .00000231  00000+0  12550-3 0  9990
2 43689  98.6738 321.3529 0003400 134.6858 225.4597 14.21519325252657
DMSP 5D-3 F16 (USA 172) 
1 28054U 03048A   23263.34797512  .00000280  00000+0  17184-3 0  9991
2 28054  99.0179 262.3704 0008391  96.9624  15.1941 14.13849910 28008
DMSP 5D-3 F17 (USA 191) 
1 29522U 06050A   23263.31728388  .00000288  00000+0  17361-3 0  9995
2 29522  98.7544 274.4244 0010629  37.5973 322.5942 14.14292059870906
DMSP 5D-3 F18 (USA 210) 
1 35951U 09057A   23263.38920944  .00000399  00000+0  23366-3 0  9992
2 35951  98.7781 237.9586 0010274 212.9423 147.1110 14.13852682718092
NOAA 15                 
1 25338U 98030A   23263.34799656  .00000289  00000+0  13818-3 0  9998
2 25338  98.6005 290.7554 0011009  41.4520 318.7494 14.26391782318821
NOAA 18                 
1 28654U 05018A   23263.37894546  .00000327  00000+0  19909-3 0  9993
2 28654  98.9029 337.2825 0015298 110.0555 250.2265 14.13009150945011
NOAA 19                 
1 33591U 09005A   23263.36460833  .00000279  00000+0  17469-3 0  9991
2 33591  99.0905 310.7732 0013356 339.1005  20.9619 14.12823802753381
FENGYUN 3A              
1 32958U 08026A   23263.40962569  .00000259  00000+0  14427-3 0  9996
2 32958  98.5640 213.9408 0009469 129.0572 231.1448 14.18918012793560
FENGYUN 3B              
1 37214U 10059A   23263.36294661  .00000154  00000+0  10422-3 0  9996
2 37214  99.0822 282.3343 0022958 135.8180 351.6642 14.14376749665961
FENGYUN 3C              
1 39260U 13052A   23263.34916345  .00000190  00000+0  11660-3 0  9998
2 39260  98.4295 272.4041 0011732  34.0601 326.1325 14.16077245516996
FENGYUN 3D              
1 43010U 17072A   23263.38336897  .00000210  00000+0  12166-3 0  9999
2 43010  98.8696 212.0575 0002392  53.0078 307.1316 14.19205407303007
FENGYUN 3E              
1 49008U 21062A   23263.36821941  .00000045  00000+0  42166-4 0  9993
2 49008  98.7270 263.4042 0002702  90.7998 269.3487 14.19697300114566
FENGYUN 3F              
1 57490U 23111A   23263.40024024  .00000152  00000+0  92732-4 0  9999
2 57490  98.8060 329.5744 0001765 118.3135 241.8219 14.19706324  6856
FENGYUN 3G              
1 56232U 23055A   23263.37264179  .00042918  00000+0  68353-3 0  9999
2 56232  49.9971 106.8077 0007809  18.4953 341.6297 15.52752829 24444
METEOR-M 1              
1 35865U 09049A   23263.36340876  .00000239  00000+0  12616-3 0  9994
2 35865  98.5911 225.6952 0002119 359.7541   0.3635 14.22546184727066
METEOR-M 2              
1 40069U 14037A   23263.41217421  .00000185  00000+0  10491-3 0  9993
2 40069  98.4277 264.9784 0006915  69.9292 290.2630 14.20813117477172
METEOR-M2 2             
1 44387U 19038A   23263.39332889  .00000099  00000+0  62746-4 0  9994
2 44387  98.7866 227.1498 0002116  52.6209 307.5161 14.23806221218855
**<HEAD><TITLE>Connection timed out</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black">
<FONT FACE="Helvetica,Arial"><B>**
 Connection timed out</B></FONT>


</BODY>
 TERRA                   
1 25994U 99068A   23263.43371956  .00000900  00000+0  19993-3 0  9997
2 25994  98.0859 329.4291 0003059 115.2822 300.9932 14.59319856263679
AQUA                    
1 27424U 02022A   23263.39164969  .00001681  00000+0  37330-3 0  9992
2 27424  98.2934 207.5173 0000817  95.4576  15.2718 14.58330255137239
AURA                    
1 28376U 04026A   23263.11841919  .00001694  00000+0  38089-3 0  9998
2 28376  98.2160 205.5357 0001236  92.9112 267.2228 14.57734385 20218
SUOMI NPP               
1 37849U 11061A   23263.40532799  .00000188  00000+0  10965-3 0  9995
2 37849  98.7084 200.5196 0001221  61.3291  55.5296 14.19568073616447
NOAA 20                 
1 43013U 17073A   23263.41755906  .00000171  00000+0  10181-3 0  9994
2 43013  98.7162 200.3817 0001012 108.0658 252.0629 14.19565145302483
NOAA 21 (JPSS-2)        
1 54234U 22150A   23263.08098261  .00000193  00000+0  11243-3 0  9994
2 54234  98.7200 199.5606 0001465 101.1864 258.9477 14.19548644 44511
<HEAD><TITLE>Connection timed out</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black">
<FONT FACE="Helvetica,Arial"><B>
 Connection timed out</B></FONT>


</BODY>
 CFOSAT                  
1 43662U 18083A   23263.39627222  .00007638  00000+0  39613-3 0  9998
2 43662  97.3941 280.1844 0002014  44.5457 315.5938 15.16427030270865
CORIOLIS                
1 27640U 03001A   23262.76082367  .00000212  00000+0  12172-3 0  9997
2 27640  98.7170 269.3413 0013512 212.6366 147.3976 14.19306034 72095
PROBA-1                 
1 26958U 01049B   23263.36136475  .00002981  00000+0  24052-3 0  9990
2 26958  97.8832 230.6724 0067261 248.6678 110.7356 14.98924839193290
PROBA-2                 
1 36037U 09059B   23263.10137696  .00000437  00000+0  11515-3 0  9990
2 36037  98.2286  86.2399 0014321 128.0146 232.2346 14.53607786736113
PROBA-V                 
1 39159U 13021A   23263.05305987  .00000128  00000+0  74703-4 0  9992
2 39159  98.3181 279.6184 0004248 170.0872 190.0392 14.23151089538698
CLOUDSAT                
1 29107U 06016A   23262.75397240  .00000727  00000+0  14717-3 0  9992
2 29107  98.3848 234.1929 0002173 335.5482  24.5616 14.64337307926373
ISS (ZARYA)             
1 25544U 98067A   23263.37806641  .00016418  00000+0  30068-3 0  9990
2 25544  51.6417 217.0147 0005763  40.8381  99.3324 15.49450674416559
CSS (TIANHE)            
1 48274U 21035A   23263.38869410  .00026560  00000+0  29075-3 0  9995
2 48274  41.4738 296.7227 0008014  63.0763 297.0895 15.62637231136711
GCOM-W1 (SHIZUKU)       
1 38337U 12025A   23263.38967819  .00001196  00000+0  27535-3 0  9992
2 38337  98.2058 202.2465 0001346  74.5334  35.7202 14.57118819603282
GCOM-C (SHIKISAI)       
1 43065U 17082A   23262.23449228  .00000274  00000+0  12975-3 0  9994
2 43065  98.6012 334.2029 0001271  96.6116 263.5210 14.27299826299019
EWS-G1 (GOES 13)        
1 29155U 06018A   23263.11903230  .00000044  00000+0  00000+0 0  9998
2 29155   1.7470  90.2807 0005023 122.2517 250.5639  1.00275901 63474
GOES 14                 
1 35491U 09033A   23262.45118472 -.00000059  00000+0  00000+0 0  9997
2 35491   0.4007 265.6530 0004121 227.2903 279.0275  1.00272116 52116
EWS-G2 (GOES 15)        
1 36411U 10008A   23263.60257626 -.00000300  00000+0  00000+0 0  9996
2 36411   0.3762 274.9996 0004541 308.5022 100.7813  0.99977519 49600
GOES 16                 
1 41866U 16071A   23263.09188126 -.00000241  00000+0  00000+0 0  9997
2 41866   0.0798 285.6032 0000497 288.2087 102.7985  1.00271951 25052
GOES 17                 
1 43226U 18022A   23263.08598650 -.00000084  00000+0  00000+0 0  9998
2 43226   0.0424 355.9448 0002016 168.1349 120.9176  1.00272099 20398
GOES 18                 
1 51850U 22021A   23263.29450017  .00000103  00000+0  00000+0 0  9992
2 51850   0.0323 341.9568 0000437 155.7781 190.2190  1.00271713  5765
ARKTIKA-M 1             
1 47719U 21016A   23261.58429289  .00000171  00000+0  00000+0 0  9996
2 47719  63.1466 182.3024 6888814 269.4773  18.1108  2.00611932 18683
ELEKTRO-L 2             
1 41105U 15074A   23263.17562734 -.00000108  00000+0  00000+0 0  9997
2 41105   4.1442  82.6835 0002559 138.2253 186.6597  1.00272389 28470
<HEAD><TITLE>Connection timed out</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black">
<FONT FACE="Helvetica,Arial"><B>
 Connection timed out</B></FONT>


</BODY>
 <HEAD><TITLE>Connection timed out</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black">
<FONT FACE="Helvetica,Arial"><B>
 Connection timed out</B></FONT>


</BODY>
 FENGYUN 2G              
1 40367U 14090A   23263.05500648 -.00000295  00000+0  00000+0 0  9993
2 40367   3.0910  84.6177 0000442 158.3536 235.3468  1.00272275 32001
FENGYUN 2H              
1 43491U 18050A   23262.74979823 -.00000119  00000+0  00000+0 0  9999
2 43491   2.3138  89.6843 0003376  93.8123 163.9820  1.00270114 19479
FENGYUN 4A              
1 41882U 16077A   23262.75052449 -.00000322  00000+0  00000+0 0  9991
2 41882   0.2193  82.6479 0002061  52.6558 237.9930  1.00268670 24948
FENGYUN 4B              
1 48808U 21047A   23262.98999501 -.00000314  00000+0  00000+0 0  9994
2 48808   0.2128  83.3469 0002861  32.1874  12.5950  1.00279321  8520
<HEAD><TITLE>Connection timed out</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black">
<FONT FACE="Helvetica,Arial"><B>
 Connection timed out</B></FONT>


</BODY>
 AIM                     
1 31304U 07015A   23262.38716410  .00036558  00000+0  11057-2 0  9991
2 31304  97.8749 209.0063 0002819 160.4995 199.6355 15.34116072901100
<HEAD><TITLE>Connection timed out</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black">
<FONT FACE="Helvetica,Arial"><B>
 Connection timed out</B></FONT>


</BODY>
 <HEAD><TITLE>Connection timed out</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black">
<FONT FACE="Helvetica,Arial"><B>
 Connection timed out</B></FONT>


</BODY>
 COSMOS 2518             
1 42719U 17027A   23263.09658394  .00000569  00000+0  00000+0 0  9998
2 42719  63.1565  25.2144 7249706 268.7475  15.4911  2.00536365 46295
HINODE (SOLAR-B)        
1 29479U 06041A   23262.77108623  .00001090  00000+0  20891-3 0  9993
2 29479  98.1048 276.8666 0017354 214.5498 145.4579 14.65673805908026
IRIS                    
1 39197U 13033A   23262.42160725  .00001793  00000+0  23914-3 0  9992
2 39197  97.9703  89.6698 0026536 345.8876  14.1591 14.80636526551873
LUCKY-7                 
1 44406U 19038W   23262.37866960  .00023861  00000+0  89747-3 0  9996
2 44406  97.6896 243.8421 0016873 344.9635  15.1099 15.27009376232684
<HEAD><TITLE>Connection timed out</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black">
<FONT FACE="Helvetica,Arial"><B>
 Connection timed out</B></FONT>


</BODY>
 OCEANSAT-2              
1 35931U 09051A   23263.38214193 -.00000010  00000+0  19204-4 0  9994
2 35931  98.3047 332.8181 0016990 177.1568 182.9697 13.99382136739343
<HEAD><TITLE>Connection timed out</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black">
<FONT FACE="Helvetica,Arial"><B>
 Connection timed out</B></FONT>


</BODY>
 SARAL                   
1 39086U 13009A   23261.85233655  .00000194  00000+0  88149-4 0  9997
2 39086  98.5499  85.7933 0002411  36.9589 323.1760 14.32259696552095
ANGELS                  
1 44876U 19092D   23263.41921869  .00007959  00000+0  34709-3 0  9991
2 44876  97.4794  87.5203 0010649 185.6440 174.4678 15.22389045208101
OTB-3-GAZELLE           
1 54023U 22127A   23261.97818672  .00000269  00000+0  95306-4 0  9993
2 54023  98.3296 257.5873 0012950 338.3622  21.7019 14.41897363 49890
SYRACUSE 3B             
1 29273U 06033B   23263.10580486 -.00000036  00000+0  00000+0 0  9991
2 29273   0.3190  93.0656 0004148  91.3226 207.2635  1.00272407 62711
SCISAT 1                
1 27858U 03036A   23262.72304308  .00001328  00000+0  18703-3 0  9999
2 27858  73.9354 356.7808 0008992 287.3760  72.6431 14.78409927 83297
YOUTHSAT                
1 37388U 11015B   23263.01484760  .00000336  00000+0  16198-3 0  9992
2 37388  98.3003 272.3770 0015606  46.4184   7.8587 14.24654910645564
SENTINEL-6              
1 46984U 20086A   23262.76162508 -.00000060  00000+0  24477-5 0  9992
2 46984  66.0419  55.0211 0007858 268.1918  91.8198 12.80929842132193
TUBIN                   
1 48900U 21059X   23263.39624095  .00014554  00000+0  65426-3 0  9996
2 48900  97.6129  37.7879 0007835 315.1229  44.9372 15.21211634123645
UMKA 1 (RS40S)          
1 57172U 23091G   23263.39185575  .00005979  00000+0  43558-3 0  9993
2 57172  97.6556 313.2674 0016684 327.9474  32.0736 15.04018736 12749
<HEAD><TITLE>Connection timed out</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black">
<FONT FACE="Helvetica,Arial"><B>
 Connection timed out</B></FONT>


</BODY>
 SMAP                    
1 40376U 15003A   23262.43781590  .00000913  00000+0  18554-3 0  9999
2 40376  98.1304 267.6768 0000974  95.3869 264.7444 14.63412389461114
CHEOPS                  
1 44874U 19092B   23262.78843123  .00000562  00000+0  13404-3 0  9996
2 44874  98.2383  89.7976 0010733 358.3344   1.7817 14.57377826199689
<HEAD><TITLE>Connection timed out</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black">
<FONT FACE="Helvetica,Arial"><B>
 Connection timed out</B></FONT>


</BODY>
 NEOSSAT                 
1 39089U 13009D   23263.09598643  .00000341  00000+0  13468-3 0  9994
2 39089  98.4087  92.5846 0011127 355.9869   4.1225 14.34932121553139
FORMOSAT-5              
1 42920U 17049A   23262.46811688  .00000411  00000+0  11566-3 0  9992
2 42920  98.3167 338.7984 0009461 286.6084  73.4072 14.50756759321423
OPS-SAT                 
1 44878U 19092F   23263.05549092  .00047555  00000+0  12039-2 0  9994
2 44878  97.4723  93.3543 0008446 147.4978 212.6789 15.39563831208362
SWOT                    
1 54754U 22173A   23263.41453559  .00000045  00000+0  32059-4 0  9993
2 54754  77.6098 306.2510 0000110  54.8992 305.2169 14.00172056 39093
PAZ                     
1 43215U 18020A   23263.37052591  .00004475  00000+0  21625-3 0  9992
2 43215  97.4467 269.1375 0001775  87.8496 272.2941 15.19137339309077
CALIPSO                 
1 29108U 06016B   23262.40921997  .00002498  00000+0  48138-3 0  9998
2 29108  98.3854 233.3424 0001514  83.5232 276.6142 14.64435723926176
<HEAD><TITLE>Connection timed out</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black">
<FONT FACE="Helvetica,Arial"><B>
 Connection timed out</B></FONT>


</BODY>
 GRACE-FO 2              
1 43477U 18047B   23262.74813337  .00004979  00000+0  18734-3 0  9990
2 43477  88.9901 336.3321 0015494  43.0659 317.1799 15.26819655296421
CRYOSAT 2               
1 36508U 10013A   23262.53582343  .00000456  00000+0  11247-3 0  9997
2 36508  92.0283  35.1649 0005778 112.8905 247.2912 14.51911460712783
PRISMA                  
1 44072U 19015A   23263.43852262  .00001691  00000+0  21127-3 0  9993
2 44072  97.8707 336.5405 0000989  82.5882 277.5445 14.83650365243668
LANDSAT 8               
1 39084U 13008A   23263.37297932  .00000746  00000+0  17557-3 0  9998
2 39084  98.2182 332.1000 0001194  95.5721 264.5613 14.57113250563975
LANDSAT 9               
1 49260U 21088A   23263.20130934  .00000773  00000+0  18171-3 0  9995
2 49260  98.2217 331.9212 0001385  92.8226 267.3131 14.57116895105229
YUNHAI 1                
1 41857U 16068A   23263.41954987  .00000513  00000+0  20330-3 0  9998
2 41857  98.5931 266.6485 0008467  81.5660 278.6483 14.33076135358502
YUNHAI 1-02             
1 44547U 19063A   23263.33373996  .00000405  00000+0  16374-3 0  9994
2 44547  98.4666 284.0068 0000262 241.4320 118.6838 14.33023061208535
YUNHAI 1-03             
1 53877U 22115A   23263.36944600  .00000486  00000+0  19359-3 0  9996
2 53877  98.5116 260.4015 0001081  67.9359 292.1940 14.33005077 52182

**Comment by Aang23** [comment]
Can you send the file as a file and not copy-paste it over?

**Comment by IZ5RZR** [comment]
> Can you send the file as a file and not copy-paste it over?
Ok here is file. just now updated from satdump, You will see many downloadings erroe that go into crash satdump
[satdump_tles.txt](https://github.com/SatDump/SatDump/files/12706873/satdump_tles.txt)

**Comment by JVital2013** [comment]
Hello @IZ5RZR!

Thanks for the TLE file. We just made two changes that should fix your problem:

- SatDump now only queries a few URLs that get multiple TLEs at once, to prevent rate-limiting
- SatDump now verifies downloaded TLEs. Instead of crashing, it will gracefully skip any TLEs it failed to download.

Please try the latest nightly at https://github.com/SatDump/SatDump/releases/tag/nightly and let us know if it works for you!

**Comment by JVital2013** [comment]
Hello again @IZ5RZR,

I see your posts on social media that this issue is now fixed for you. I'm going to go ahead and close this, but feel free to reach out if it acts up again!
