### ISSUE TITLE
How to use satdump to decode any PSK modulated signal?

### ISSUE THREAD

**Issue by ghost** [SatDump/SatDump#456]
Hello, can I use satdump as a simple decoder for bpsk/qpsk modulation with known parameters? I generate bpsk data with gnuradio as in the screenshot below, then record it. Afterwards, I would like to decode it with satdump. However, satdumps only works with pipelines that are defined parameters for some satellites as far as I understand. Is there any option that I can adjust parameters (sample rate, symbol rate, rrc alpha) freely in the released version? If I have to change the code and build it for my problem, where should I start?
![bpskMod](https://github.com/SatDump/SatDump/assets/69161854/b548a883-5f1a-440d-b20f-3c09773fedf9)

**Comment by ZbychuButItWasTaken** [comment]
Yes, it is pretty easy to do actually!
All you need to do, is define a pipeline in the /pipelines/ folder, in one of the json files. You don't even need to recompile it!
You can have a look on the existing pipelines to see how the parameters are defined, here is a simple BPSK example from `proba.json`

```
"proba1_dump": {
        "name": "Proba-1 Dump",
        "live": true,
        "live_cfg": [
            [
                1,
                0
            ],
            [
                2,
                0
            ]
        ],
        "frequencies": [
            [
                "Dump",
                2235e6
            ]
        ],
        "parameters": {
            "samplerate": {
                "value": 4e6
            }
        },
        "work": {
            "baseband": {},
            "soft": {
                "psk_demod": {
                    "constellation": "bpsk",
                    "symbolrate": 2e6,
                    "rrc_alpha": 0.5,
                    "pll_bw": 0.004
                }
            },
            "cadu": {
                "ccsds_conv_concat_decoder": {
                    "constellation": "bpsk_90",
                    "cadu_size": 10232,
                    "viterbi_ber_thresold": 0.300,
                    "viterbi_outsync_after": 20,
                    "derandomize": false,
                    "rs_i": 5,
                    "rs_type": "rs223"
                }
            },
            "products": {
                "proba_instruments": {
                    "satellite": "proba1"
                }
            }
        }
    }
    ```
    
    All you really care about is the `work` part, specifically the "soft" section. The demod will output soft symbols. If you delete all the other steps, like `cadu` or `products` it'll finish the processing after decoding to soft.
    Hope this helps.

**Comment by Aang23** [comment]
If the preamble is something like a 32-bits syncword as regular interval, you can use the CCSDS "simple PSK decoder" for this purpose.

And yes, this is correct. No need to store the 2 channels for BPSK when we want soft symbols.
