### ISSUE TITLE
enable bias tee?

### ISSUE THREAD

**Issue by benb0jangles** [SatDump/SatDump#47]
do I use: 
SoapySDRUtil --probe="driver=airspy,biastee=true
before launching satdump live processing?
Or is there another way in satdump?
Thanks

**Comment by K4KDR** [comment]
Hello!  Once the GUI is started, there is a 'check-box' to enable the Bias-Tee (or not) in the "Airspy Control" section...

![satdump-biastee](https://user-images.githubusercontent.com/19886368/137227920-717d665a-618b-4931-8f6d-0891d6e3abe8.png)
