### ISSUE TITLE
NOAA APT network streaming pipeline

### ISSUE THREAD

**Issue by f6bvp** [SatDump/SatDump#474]
NOT all pipelines are not currently supported in Server/Client - Network streaming.
Would you please add NOAA APT pipeline in that mode ?

Question : is client mode supported by satdump-ui ? I tried different "File Source" devices (RTL-TCP, SDR++ Server,...) in the list without success, while console mode --client is ok with goes live server example is running.

Regards,

Bernard, f6bvp / ai7bg

**Comment by JVital2013** [comment]
Thanks for the request to add APT to the client/server network streaming feature. This is solidly in @Aang23's territory so I'll leave this request for him.

No, client mode is not currently supported in the UI. Right now it is CLI only. I know I have looked for this feature myself though.

**Comment by Aang23** [comment]
The intent with the Server/Client scheme was rather on 24/7 stations, such as geostationary satellites where it can be handy to run part of the system say, on a Pi right under the antenna and the rest, where the images/etc are dumped.

For the case of APT and other LEOs, it was rather intended to rather stream baseband or decode fully on the "source".

**Comment by Aang23** [comment]
Considering this is not really a feature that makes sense in most cases - I will close the issue.
