### ISSUE TITLE
Device after restart is gone

### ISSUE THREAD

**Issue by georgjorge** [SatDump/SatDump#476]
**What would you want to be added to satdump?**
A clear and concise description of what the idea/problem is.

**Describe the feature you'd like to have**

**Describe alternatives you've considered**

**Additional context**
Here you can for provide more information about what you'd like to see as the end result. Feel free to also post images if you have ideas regarding the UI

**Comment by georgjorge** [comment]
Hello,
when I restart SatDump my device is gone. Is this a regular behavior?

**Comment by JVital2013** [comment]
Sorry, we will need more details here. What do you mean by "your device is gone?"

**Comment by georgjorge** [comment]
Manually, I choos RTL-2832 as input device. After restarting the program, the input device was cleared.

**Comment by JVital2013** [comment]
Ah, I understand now, thanks! Yes, this is currently how the software is designed to work.

**Comment by georgjorge** [comment]
Thank you for the information!
George

**Comment by JVital2013** [comment]
Hi @georgjorge,

Sorry for letting this sit for so long! We have implemented a change so SatDump now remembers the last used SDR. This change will be a part of 1.1.3
