### ISSUE TITLE
error opening dataset

### ISSUE THREAD

**Issue by georgjorge** [SatDump/SatDump#477]
Hi, 
I am still struggling with SatDump. I am not able to decode the received data from noaa 15 with format f32 and also noaa 18 with format .wav.
Always I get an exception-parse-error 101 at line 1 column 1, syntax error while parsing value - invalid literal, last read ´R´. Could anyone point me to set the correct parameter for decoding the file?
Further more I am not able to get an automatic start to receive satellites even though it was scheduled.

George

**Comment by JVital2013** [comment]
You cannot decode basebands with the viewer screen - you should use the "offline processing" screen for that. The viewer screen is for opening dataset.json/product.cbor files from already-processed data.

I'd recommend reviewing this web page to get started: https://www.satdump.org/posts/basic-usage/

**Comment by georgjorge** [comment]
Thank you for your quick answer, but I still does not get an picture with offline processing. I tried noaa apt, dsb and gac decoder with input level basement. With noaa apt it says error 302. With dsb decoder it reports "none of the channel is present".  The signal is approximately 12 dB over noise. The basic-usage document does not help me. Sorry molesting you.
George

**Comment by JVital2013** [comment]
**Let's start with the NOAA 15 f32 recording you have.** I'm assuming you got it's APT signal on 137.62 MHz? Set up SatDump like this. If the signal was not centered in the baseband when you recorded it, you'll need to set a frequency shift.

![image](https://github.com/SatDump/SatDump/assets/24253715/1708796a-fc8b-4980-8bab-cb74303b04a9)

**For the NOAA 18 that's a wav:** is this a baseband wav, or an audio wav (where you can hear the ticking)? If it's an audio wav, you need to set satdump up like this:

![image](https://github.com/SatDump/SatDump/assets/24253715/b79fb73d-2e02-40b7-8520-8278b8fbb673)

**Comment by JVital2013** [comment]
Hi @georgjorge, would you like any further assistance with this issue?

**Comment by Aang23** [comment]
I'll close this for now. I'll gladly re-open on any further reply.
