### ISSUE TITLE
  Build error: Unknown CMake command "add_compile_definitions"

### ISSUE THREAD

**Issue by benb0jangles** [SatDump/SatDump#48]
Hi, I'm trying to compile for Aarch64 Jetson Nano

I have this error when compiling:

```
~/satdump/build$ cmake -DBUILD_LIVE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..

CMake Error at CMakeLists.txt:9 (add_compile_definitions):
  Unknown CMake command "add_compile_definitions".

-- Configuring incomplete, errors occurred!
```

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

cmake --version
cmake version 3.10.2

Arm/Aarch64 Jetson Nano

**Comment by Aang23** [comment]
Indeed, Ubuntu 18.04 is getting old... And ships with a very outdated CMake by modern standards.
I could theorically support it if this became a larger issue, but to be fair as I saw in your second issue, CMake is not the only issue and a C++-compliant compiler is required, at least GCC 8 if I'm not mistaken.

**Comment by noloader** [comment]
https://stackoverflow.com/q/61250087
