### ISSUE TITLE
Tracking display is broken

### ISSUE THREAD

**Issue by db2os** [SatDump/SatDump#483]
Recently the AZ/EL diagram is showing strange behavior, in particular with objects from Horizons.
Latest release..

![Screenshot 2023-11-12 095440](https://github.com/SatDump/SatDump/assets/53628992/bccc0c65-f921-46a2-8cc6-9bac3930057a)

**Comment by JVital2013** [comment]
This has been fixed - please update to the latest nightly and try again. If it still happens, let us know.

Thanks for the report!

**Comment by db2os** [comment]
@JVital2013 it seems there is a new issue..   at LOS (Elevation < 0) the display is cleared and does not show any updates and next AOS time..
![Screenshot 2023-11-14 142018](https://github.com/SatDump/SatDump/assets/53628992/3a59bc40-b05b-4d55-9ef1-8fa21d2ffa15)

**Comment by JVital2013** [comment]
Update to the latest nightly and try again - I was able to reproduce the issue and fix it on my end, but I'd like to make sure it works for you too.

**Comment by db2os** [comment]
Thanks @JVital2013 - it seems to work fine now..

**Comment by JVital2013** [comment]
Great, glad to hear it!
