### ISSUE TITLE
Mute option for decoders with audio output

### ISSUE THREAD

**Issue by variorex** [SatDump/SatDump#499]
**Describe the feature you'd like to have**
Since some decoders like the NOAA APT decoder enable audio output when a signal is being processed live within the "recorder"-tab, an option to mute the satdump audio output would be really useful.
In my usecase with satdump running in the background in tracking mode, I always get a minor heart attack when the APT decoder automatically enables itself and the pretty loud decoder noise comes on😁 

**Describe alternatives you've considered**
Muting the entire PC audio output.

**Additional context**
I think a simple checkbox-based option to mute the audio output or something like a volume slider would be very nice. Also, making the last state of the mute-option/slider position "non-volatile" so that after closing and reopening satdump that state is still enabled, would make the usage even more smoother.

Thanks 😄

**Comment by klhutchins1** [comment]
"I always get a minor heart attack when the APT decoder automatically enables itself and the pretty loud decoder noise comes on". haha, that brought me here for this reason as well.

**Comment by RAD750** [comment]
An additional workaround for the time being is muting SatDump only from the audio control panel of your operating system.
For example, on Linux: 
![immagine](https://github.com/SatDump/SatDump/assets/12469744/56980e9d-c685-4328-ab2f-388f4d64afe6)

On Windows the process is similar.

**Comment by JVital2013** [comment]
Well, we can't have SatDump be the cause of any coronary events. Grab the latest nightly - I just added an button to the decoder to turn the audio on/off during the decode:

![audio toggle](https://github.com/SatDump/SatDump/assets/24253715/4b22e72b-a7d2-4974-8c09-874783d20864)

Toggling this setting only affects the current decode. To set the default, change this option on the settings screen:

![image](https://github.com/SatDump/SatDump/assets/24253715/468b25a1-2901-4db6-93d1-b86338b9a61a)

Thanks for the feedback!
