### ISSUE TITLE
SDR Bias T not shot down (deactivated) when closing satdump-ui

### ISSUE THREAD

**Issue by f6bvp** [SatDump/SatDump#525]
Using satdump-ui with a RTL-SDR.COM model V3 that has Bias-T capability and it works fine to turn on 5V DC on sma antenna plug for Nooelec preamplifier alimentation.

However if I shutdown satdump-ui without clicking prealably on bias button to stop bias-t it is not switched off (preamplifier LED remains lighted). This means that SDR bias is left activated even without any application working.

I think this should be added in the shutdown part of satdump-ui together with (who kows ?) stopping sdr as if user had also cliked on stop button.

Thanks for such a nice application !

73 de Bernard, f6bvp

**Comment by f6bvp** [comment]
Sorry ! shut down would be better than shot down !!!

**Comment by ZbychuButItWasTaken** [comment]
hmmm, I don't think there is an easy way to do that, unless we disable the bias-tee every time when stopping the SDR.
@Aang23 what are your thoughts on this?

**Comment by JVital2013** [comment]
In my opinion, this makes sense to me - an SDR shouldn't be putting out voltage after it's been told to stop. At least, in my use-cases, this would made sense. The same probably goes for other SDRs with a switchable Bias-T.

It could probably be added into the `stop()` methods.

**Comment by Aang23** [comment]
It's definitely doable and a good point. Will be added soon.
