### ISSUE TITLE
Is audio available remotely when using satdump_sdr_server

### ISSUE THREAD

**Issue by f6bvp** [SatDump/SatDump#526]
I read that audio what possibly disabled or enabled when processing NOAA APT FM decoding.
Is audio sound available on satdump-ui client connected to remote satdump_sdr_server ?
Alan already explained me that APT pipeline streaming was not an option.
However could audio AM or FM be provided independently from APT pipeline ?
If not, how could I pipe satdump-ui client stream to local audio ?

Best regards,

Bernard, f6bvp

**Comment by Aang23** [comment]
Do you mean with satdump_sdr_server on your remote machine and satdump-ui on a local one? If so, yes it will work as normal.

However if you're running it remotely, say through Anydesk or such, it rather falls upon say remove access SW to forward audio.

**Comment by f6bvp** [comment]
Yes I am using : satdump_sdr_server on remote machine and satdump-ui on a local one.
I found Play Audio in Setting on local satdump-ui .
Is is selected but I do not get any audio output.

What do you mean by "remove access SW to forward" ?

Bernard
 

![Capture d’écran du 2023-11-23 20-38-45](https://github.com/SatDump/SatDump/assets/14106669/67c7d443-35ad-4c67-bd36-5d35cf11c1f6)

**Comment by JVital2013** [comment]
The "play audio" setting only affects two processing pipelines right now: NOAA APT and Inmarsat Aero. Audio is played when these pipelines are active.

Otherwise, SatDump currently does not have any other support for Audio output.
