### ISSUE TITLE
Could "Save" button aspect change when it is clicked ?

### ISSUE THREAD

**Issue by f6bvp** [SatDump/SatDump#530]
I feel frustrated and a little bit anxious when clicking on "Save" button of satdump-ui menu "Settings" nothing happens.
Changing its color or any other aspect could confirm the success of saving settings.

Bernard, f6bvp

**Comment by RAD750** [comment]
If you look at the bottom of the screen you'll see it did save
![immagine](https://github.com/SatDump/SatDump/assets/12469744/e53926ee-8403-4286-bfef-fb69349d697e)

But I guess @JVital2013 maybe can add a green "Save Successful" text near to the save button for more clarity.

**Comment by JVital2013** [comment]
Yep something like this will be added soon!
