### ISSUE TITLE
Decimation count stops at 1 when pushing minus sign 

### ISSUE THREAD

**Issue by f6bvp** [SatDump/SatDump#543]
Pushing satdump-ui decimation +/- increments or decrements value by one.
However it will never return to zero .

This seams to me a typical NRZ bug for PSK demodulor gurus 

(smiley) !

73 de Bernrd, f6bvp / ai7bg

**Comment by f6bvp** [comment]
By the Way.
Is decimation only working for spectrum display or doing actually decimation of saved file ?

**Comment by Aang23** [comment]
Decimation never going under 1 is the expect behavior. What is the issue exactly?

No the entire IQ is decimated, this covers the spectrum and basebands.

**Comment by f6bvp** [comment]
Sorry, I wrongly thought it was 0 at first start.
Please excuse my stupid remark.
Bernard
