### ISSUE TITLE
Total App Freeze when Engaging Autotrack

### ISSUE THREAD

**Issue by burgeda** [SatDump/SatDump#548]
Compiling and running on Rocky 9.3 has been working successfully up until Dec 11th.
Clone from git and compiling work and satdump seemed fine but I've noticed that since Dec 11th and a couple of commits related to autotrack that while it still seems to compile fine the app will lock up solid whenever I try and select "Engage Autotrack".  The check mark doesn't even appear in the checkbox.  The app is locked up solid and must be killed and restarted.  All other features I've tried so far seem to still work.

The last entry in the log is always "(T) Update pass trajectory..."

I've downloaded the tarball for 1.1.2, compiled it on the same machine and everything is fine, I believe it's definitely related the the autotrack commits.

**Comment by JVital2013** [comment]
Fixed - thanks for the report!
