### ISSUE TITLE
Please sort alphabetically pipelines list in satdump-ui "Processing"

### ISSUE THREAD

**Issue by f6bvp** [SatDump/SatDump#552]
Well, I think the title speaks for himself.
Presently choosing the right pipeline is a little bit tedious...
As "Favourites" list will stay probably small, there is probably no need to sort them.

Bernard

**Comment by JVital2013** [comment]
Thanks for the feedback! This change is in place, effective as of commit 99fb0d2b. The Favorites list is sorted in the order they are added, and I think it makes sense to keep it that way.
