### ISSUE TITLE
Confusion between Waterfall and FFT Rates displayed on local console

### ISSUE THREAD

**Issue by f6bvp** [SatDump/SatDump#578]
When clicking on -/+ FFT Rate button -1
local satdump-ui console goes from 120 to 119 : 
[16:12:21 - 02/01/2024] (I) Set Waterfall rate to 119
however
When clicking on Waterfall -/+ Rate button it goes down from say 59 to 58
but satdump-ui console displays invariably message : 
[16:12:21 - 02/01/2024] (I) Set Waterfall rate to 119
Same if +1 is clicked

Conclusion : message on console always actually display 
(I) Set Waterfall rate to xx 
xx being the value of FFT rate and not Waterfall rate

**Comment by JVital2013** [comment]
Fixed - was just a bug in the logging
