### ISSUE TITLE
SPS invalid - no NOAA APT constellation or image

### ISSUE THREAD

**Issue by gm8arv** [SatDump/SatDump#580]
Just updated to the nightly Windows build, although I don't know whether that's related.  Was working fine before.  Issue now is that I'm getting no NOAA APT display ("constellation", image etc.), and a message in the status bar "SPS is invalid, Must be above 1!"  The spectrum and waterfall are correct (HF+ 192 ksps/4).  So which SPS might be wrong, and where might I find it?  I can't see anything immediately wrong in the .json file.

**Comment by gm8arv** [comment]
Here's setting.json......

{
    "user_interface": {
        "play_audio": {
            "value": false
        },
        "open_viewer_post_processing": {
            "value": false
        },
        "remember_pos": {
            "value": true
        },
        "window": {
            "maximized": false,
            "x": 332,
            "y": 51,
            "xs": 1250,
            "ys": 882
        }
    },
    "satdump_general": {
        "opencl_device": {
            "platform": 1
        },
        "qth_lat": {
            "value": 55.9
        },
        "qth_lon": {
            "value": -3.2
        },
        "qth_alt": {
            "value": 180.0
        },
        "default_borders_color": {
            "value": [
                0.0,
                1.0,
                0.0
            ]
        },
        "default_shores_color": {
            "value": [
                1.0,
                1.0,
                0.0
            ]
        },
        "default_cities_color": {
            "value": [
                1.0,
                0.0,
                0.0
            ]
        },
        "default_qth_color": {
            "value": [
                1.0,
                0.0,
                1.0
            ]
        },
        "default_latlon_color": {
            "value": [
                0.0,
                0.0,
                1.0
            ]
        }
    },
    "satdump_directories": {
        "recording_path": {
            "value": "C:\\Tools\\SatDump\\output"
        },
        "live_processing_path": {
            "value": "C:\\Tools\\SatDump\\live_output"
        },
        "default_input_directory": {
            "value": "C:\\Users\\win-8\\OneDrive\\Documents"
        },
        "default_output_directory": {
            "value": "C:\\Users\\win-8\\OneDrive\\Documents"
        },
        "default_image_output_directory": {
            "value": "C:\\Users\\win-8\\OneDrive\\Documents"
        },
        "default_projection_output_directory": {
            "value": "C:\\Users\\win-8\\OneDrive\\Documents"
        }
    },
    "plugin_settings": {
        "remote_sdr_support": []
    },
    "user": {
        "tles_last_updated": 1704272944,
        "recorder_state": {
            "fft_avgn": 10.0,
            "fft_max": -100.0,
            "fft_min": -150.0,
            "fft_rate": 120,
            "fft_size": 8192,
            "panel_ratio": 0.17154471576213837,
            "select_sample_format": 3,
            "show_waterfall": true,
            "waterfall_palette": "Classic",
            "waterfall_rate": 60,
            "waterfall_ratio": 0.7362055778503418
        },
        "viewer_state": {
            "panel_ratio": 0.23000000417232513,
            "cities_type": 0,
            "cities_size": 50,
            "cities_scale_rank": 3,
            "borders_color": [
                0.0,
                1.0,
                0.0
            ],
            "shores_color": [
                1.0,
                1.0,
                0.0
            ],
            "cities_color": [
                1.0,
                0.0,
                0.0
            ],
            "latlon_color": [
                0.0,
                0.0,
                1.0
            ],
            "save_type": "png",
            "projections": {
                "projections_current_selected_proj": 2,
                "projections_equirectangular_br_lat": -90.0,
                "projections_equirectangular_br_lon": 180.0,
                "projections_equirectangular_tl_lat": 90.0,
                "projections_equirectangular_tl_lon": -180.0,
                "projections_image_height": 2048,
                "projections_image_width": 2048,
                "projections_mode_radio": 0,
                "projections_overlay_settings": {
                    "borders_color": [
                        0.0,
                        1.0,
                        0.0
                    ],
                    "cities_color": [
                        1.0,
                        0.0,
                        0.0
                    ],
                    "cities_scale": 50,
                    "cities_scale_rank": 3,
                    "cities_size": 50,
                    "cities_type": 0,
                    "draw_cities_overlay": true,
                    "draw_latlon_overlay": false,
                    "draw_map_overlay": true,
                    "draw_qth_overlay": false,
                    "draw_shores_overlay": false,
                    "latlon_color": [
                        0.0,
                        0.0,
                        1.0
                    ],
                    "qth_color": [
                        1.0,
                        0.0,
                        1.0
                    ],
                    "shores_color": [
                        1.0,
                        1.0,
                        0.0
                    ]
                },
                "projections_stereo_center_lat": 55.900001525878906,
                "projections_stereo_center_lon": -3.200000047683716,
                "projections_stereo_scale": 2.0,
                "projections_tpers_alt": 30000.0,
                "projections_tpers_ang": 0.0,
                "projections_tpers_azi": 0.0,
                "projections_tpers_lat": 0.0,
                "projections_tpers_lon": 0.0
            }
        },
        "recorder_sdr_settings": {
            "AirSpyHF dd52d780342f4af7": {
                "agc_mode": 0,
                "attenuation": 0,
                "engage_autotrack": true,
                "hf_lna": false,
                "source": "AirSpyHF",
                "start_recorder_device": true,
                "samplerate": 192000,
                "frequency": 137100000,
                "xconverter_frequency": 0.0,
                "decimation": 4
            }
        },
        "recorder_tracking": {
            "enabled_objects": [
                {
                    "norad": 33591,
                    "frequency": 137100000,
                    "record": false,
                    "live": true,
                    "pipeline_name": "noaa_apt",
                    "pipeline_params": {
                        "autocrop_wedges": false,
                        "dc_block": false,
                        "freq_shift": 0,
                        "iq_swap": false,
                        "satellite_number": "19",
                        "sdrpp_noise_reduction": false,
                        "start_timestamp": -1.0
                    }
                },
                {
                    "norad": 25338,
                    "frequency": 137620000,
                    "record": false,
                    "live": true,
                    "pipeline_name": "noaa_apt",
                    "pipeline_params": {
                        "autocrop_wedges": false,
                        "dc_block": false,
                        "freq_shift": 0,
                        "iq_swap": false,
                        "satellite_number": "15",
                        "sdrpp_noise_reduction": false,
                        "start_timestamp": -1.0
                    }
                }
            ],
            "rotator_update_period": 1.0,
            "min_elevation": 20.0,
            "rotator_config": {
                "rotctl": {
                    "address": "127.0.0.1",
                    "port": 4533
                }
            },
            "rotator_algo": {
                "park_position": {
                    "az": 0.0,
                    "el": 0.0
                },
                "park_while_idle": false,
                "unpark_at_minus": 60.0,
                "update_period": 1.0
            }
        }
    },
    "cli": {
        "engage_autotrack": true,
        "source": "AirSpyHF",
        "start_recorder_device": true
    }
}

**Comment by gm8arv** [comment]
I wonder whether the combination of 192 ksps and 4 decimation is the issue?  This results in an error recorded in the log file as the audio sample rate is 50 ksps.  Is the audio sample rate fixed, or it it /easy/ to change to 48000 ksps?  Could making the receiver bandwidth less by using a 192/4 sample rate rather than 256/4 be helpful?

"recorder_sdr_settings": {
"samplerate": 192000,
"decimation": 4

[06:52:20 - 04/01/2024] (I) Module noaa_apt_decoder
[06:52:20 - 04/01/2024] (D) Parameters :
[06:52:20 - 04/01/2024] (D)    - audio_samplerate : 50000.0
[06:52:20 - 04/01/2024] (D)    - autocrop_wedges : false
[06:52:20 - 04/01/2024] (D)    - baseband_format : "f32"
[06:52:20 - 04/01/2024] (D)    - buffer_size : 1000000
[06:52:20 - 04/01/2024] (D)    - samplerate : 48000
[06:52:20 - 04/01/2024] (D) Input SPS : 0.960000
[06:52:20 - 04/01/2024] (D) Resample : 1
[06:52:20 - 04/01/2024] (D) Samplerate : 50000.000000
[06:52:20 - 04/01/2024] (D) Dec factor : 0.960000
[06:52:20 - 04/01/2024] (D) Final SPS : 1.000000
[06:52:20 - 04/01/2024] (E) SPS is invalid. Must be above 1!

**Comment by gm8arv** [comment]
Setting the Airspy HF+ Discovery to 265/4 did the trick.

**Comment by Aang23** [comment]
This seemed weird to me at first, but is because the APT module requires at least 50kHz. 

As a note you don't need to decimate manually in the recorder outside of display preferences, the APT demodulator will do it internally anyway.

And while at it - happy new year!

**Comment by smargle9343** [comment]
I'm having this issue while trying to demodulate meteor m2-3 lrpt. it just wont work. I'm using a wav file for the input, and I'm also using the nightly...... could that have something to do with the error?
