### ISSUE TITLE
Auto TLE update not working

### ISSUE THREAD

**Issue by Sakagraisse** [SatDump/SatDump#582]
The auto TLEs update with NORAD active.txt is not anymore working due to the url being down.

Woule it be possible to add a way to create and copy paste our own TLE somewhere ? 
If it is already possible to do it, could it be added to the documentation ?

Thanks a lot for your program and your time !

MacBook Air M2 and XPS 17 9710

**Comment by JVital2013** [comment]
Please update to a nightly build from the releases page to resolve this issue, or build from master. 

We plan on releasing 1.1.3 soon, which will also fix the issue.
