### ISSUE TITLE
SARSAT.json (project is just for my own training)

### ISSUE THREAD

**Issue by f6bvp** [SatDump/SatDump#586]
After looking at some json files I created  SARSAT.json.
It is partially dummy particularly for the decoder.
SARSAT are broadcasting Manchester (a kind of BPSK with a residual carrier) 2400 bauds beacons on 1544.5 MHz. 
I choosed 480 KHz sample frequency, 16 bits depth and saving wav16 file.
To avoid DC, central frequency is 1544.530 MHz and LO 30 KHz.
SARSAT.json help me to set most local satdump-ui parameters while remote satdump_sdr_server is on the roof of F4KLO radio Club in La Villette. Antenna is a patch with Nooelec preamplifiers for 1540 MHz. It works great !

I started to build a GNURadio grc flowgraph that reads saved wav file and performs offline PLL tracking and Xlating FIR filtering.
It is designed after Daniel Estevez Euclid decoder.
However it is not yet extracting symbols ...

{
    "sarsat_l_band": {
        "name": "SARSAT Band-L",
        "live": true,
        "live_cfg": [
            [
                1,
                0
            ],
            [
                2,
                0
            ]
        ],
        "frequencies": [
            [
                "SARSAT TLM",
                1544.5e6
            ]
        ],
        "samplerate": 480e3,
        "work": {
            "baseband": {},
            "soft": {
                "psk_demod": {
                    "constellation": "bpsk",
                    "symbolrate": 2400,
                    "rrc_alpha": 0.5,
                    "pll_bw": 0.03
                }
            },
            "products": {
                "elektro_lrit_data_decoder": {}
            }
        }
    }
}

=:=:=:

Bernard
p.s. : I have not been able to find any json parameters general description.

**Comment by jensolsson** [comment]
@t6bvp what is the status of this json-file? Did it ever work?
