### ISSUE TITLE
Installer doesn't remember the previous install location.

### ISSUE THREAD

**Issue by gm8arv** [SatDump/SatDump#587]
In all (as far as I know) versions, the installer notes that you have an existing installation but, when offering to overwrite and existing install it doesn't use the correct directory.  I have SatDump in C:\Tools\ rather than C:\Program Files, so unless I happen to spot this, I get my update installed in Program Files rather than Tools.  Perhaps you could consider this an enhancement, but I feel it's an inconsistency

Congratulations on the continuing updates and your new 1.1.1 release!

**Comment by JVital2013** [comment]
Good point - this is fixed as of the latest nightly build. If you run the installer while SatDump is already installed, it will use the previously-used directory.
