### ISSUE TITLE
satdump-ui  does not disconnect and stop streaming after recording a satellite pass

### ISSUE THREAD

**Issue by f6bvp** [SatDump/SatDump#595]
When some satellite pass are selected in menu Schedule and Config for Live and record the application satdump-ui starts at AOS but does not stop streaming and does no disconnect from remote satdump_sdr_server.

**Comment by f6bvp** [comment]
at LOS of satellite

**Comment by JVital2013** [comment]
This isn't really a bug - it's simply not designed to shut down the SDR when the pass completes at this point. That can be changed, though. 

What are your thoughts on this @Aang23? I've gotten a few requests for this personally. Perhaps it should be an option in the scheduler config?

**Comment by f6bvp** [comment]
I don't know exactly how this is managed. Connection followed by SDR start and streaming ?
If SDR is started at AOS , SDR should be stopped at LOS by disconnecting.
Letting the streaming open after LOS is very bandpass consuming on the network when working remotely.

**Comment by Aang23** [comment]
Indeed at the moment it is not designed to shutdown the SDR at all. It starts it mainly to avoid user error. Though yes, as there have been many requests to do so it'd make sense to implement a simple checkbox to change this behavior.

Both make sense to be kept as depending on the SDR, keeping it running can increase reliability. Take something such as SDRPlays, it is not uncommon for them to fail to stop/restart (despite being reliable when streaming) which would be an issue on this kind of setup.

**Comment by JVital2013** [comment]
This has been implemented with the latest nightly - you can find the setting in the Tracking Configuration.

![image](https://github.com/SatDump/SatDump/assets/24253715/4821a6f3-7c07-4706-863b-72139cd81b5c)
