### ISSUE TITLE
Update command args for live goes_hrit in official docs

### ISSUE THREAD

**Issue by TheRealBanana** [SatDump/SatDump#604]
Hello, I noticed that on the official documentation page for the command-line usage it has an example for goes_hrit that is missing an 'e6' after the frequency value. Currently if you just copy and paste the example you get 0 dB SNR output. With the added e6 it should read:

`satdump live goes_hrit output_test_wtf --source rtlsdr --samplerate 2.4e6 --frequency 1694.1e6 --gain 40 --http_server 0.0.0.0:8080`

The page its on: https://www.satdump.org/posts/basic-usage/#live-processing

I wasn't sure where to report this, its so minor. I just had some trouble figuring it out when I blindly copied the command. Was hoping to save anyone else from the same trouble.

**Comment by JVital2013** [comment]
Good catch! The documentation has been updated
