### ISSUE TITLE
The actual frequency of the setting at LO Frequency offset

### ISSUE THREAD

**Issue by Aybarnur** [SatDump/SatDump#605]
The signal receiving from the insat-3dr satellite in Windows 8.1.
I use a  in C-band LNB-converter with LO=5950 MHz.
The received frequency is 4781.5 MHz, in the converter it's subtracted from the LO frequency: 5950 - 4781.5 = 1169.5 MHz.

With unadjusted tuning scale, reception is successful at the frequency 1169.5 MHz.
![20240119_insat3dr_plutoplusip_noLO](https://github.com/SatDump/SatDump/assets/154206911/2525d809-bcf9-464d-857c-6fba583b9ae6)

If I set LO Frequency offset 5950 in the LO field, then the scale shows the actual reception frequency of 4781.5 MHz.
![20240119_insat3dr_plutoplusip_LO](https://github.com/SatDump/SatDump/assets/154206911/d975866f-f6af-430b-bdb7-e2d8f3ad7944)

However, there is no reception and I find a strange value in the log:
[07:11:21 - 19/01/2024] (T) Using PlutoSDR IP Address 192.168.64.61
[07:11:21 - 19/01/2024] (D) Set PlutoSDR samplerate to 8000000
[07:11:22 - 19/01/2024] (D) Set PlutoSDR frequency to 485532704
[07:11:22 - 19/01/2024] (D) Set PlutoSDR gain to 33, mode manual
[07:11:22 - 19/01/2024] (T) FFT Rate 66666, Samplerate 8000000, Final Size 65536, Skip 1130
[07:11:36 - 19/01/2024] (I) Waiting for the thread...
[07:11:36 - 19/01/2024] (I) Thread stopped
[07:11:36 - 19/01/2024] (I) Saving user config at ./config/settings.json

![20240119_insat3dr_log](https://github.com/SatDump/SatDump/assets/154206911/2a716cb4-2bda-4ee5-b824-3483f47c862e)

**Comment by JVital2013** [comment]
There is a slight mistake in your math: 5950 - 4781.5 = 116**8**.5, not 116**9**.5. Minor point, but I thought I'd bring it up.

If you set the LO field to 5950, then you want to put the **actual** frequency of the satellite in the frequency field. SatDump will do the math for you. The UI will show the actual frequency you're receiving over the air, and the SDR is tuned to the correctly shifted frequency, as shown here:

![image](https://github.com/SatDump/SatDump/assets/24253715/5aee975f-bc08-4643-8210-2451f336238c)

**Comment by Aybarnur** [comment]
Thank you, it really was my mistake in calculations. Now I'm using the correct value and everything is working fine.
I would also like to interesting if there is any news about the processing of data and get images from this satellite?

![20240206_insat-3dr_LO](https://github.com/SatDump/SatDump/assets/154206911/05f54355-f22f-4756-aeed-b7ab2abca94f)

**Comment by JVital2013** [comment]
Glad to hear it's working for you! Unfortunately there's no interesting news on that satellite as of now; we will update #436 once there is progress
