### ISSUE TITLE
Can't use SDR# baseband recording with satdump?

### ISSUE THREAD

**Issue by Imagineer7** [SatDump/SatDump#607]
I have recorded a Meteor M2-3 LRPT signal with SDR#'s baseband recorder but, it saves it as a .wav format and I don't see an option in SatDump for WAV baseband recordings. Is there a way I can get the recorded signal to a format satdump can use? Or some other way to decode the LRPT signal.

**Comment by Aang23** [comment]
Simple input it as a baseband and it will work. SatDump will auto-select the right format. WAV is a container for the actual data.

**Comment by Aang23** [comment]
I will close this - if you have any further question I will re-open.
