### ISSUE TITLE
Run satdump_sdr_server without a config file

### ISSUE THREAD

**Issue by burgeda** [SatDump/SatDump#610]
**What would you want to be added to satdump?**
A clear and concise description of what the idea/problem is.

**Describe the feature you'd like to have**

**Describe alternatives you've considered**

**Additional context**
Here you can for provide more information about what you'd like to see as the end result. Feel free to also post images if you have ideas regarding the UI

**Comment by burgeda** [comment]
Right now when running satdump_sdr_server on a remote headless box such as a pi the satdump_sdr_server refuses to run without a /home/satdump/.config/satdump directory.
It doesn't actually write to that directory but it MUST be there for it to run.
When running this way it's best from a security point of view to run as a user with no login.

Can satdump_sdr_server be modified to not require this empty directory or perhaps have an option to specify where to find it?

**Comment by JVital2013** [comment]
I just pushed an update that should let SatDump SDR server run without this directory; please update and let us know if it works as expected for you!
