### ISSUE TITLE
"Could not fetch data from Horizons"

### ISSUE THREAD

**Issue by K4KDR** [SatDump/SatDump#615]
Running **v1.1.4-c6a7dc70** on Ubuntu 18.04.....

No doubt I'm overlooking some obvious mistake on my part, but in the **Recorder** tab, down in the **Tracking** section, when I click the **Horizons** button, I get an long list of:

```
[14:46:14 - 30/01/2024] (T) Pulled 0 Horizons objects!
[14:46:14 - 30/01/2024] (T) Update pass trajectory...
[14:46:14 - 30/01/2024] (T) Pulling Horizons data...
[14:46:14 - 30/01/2024] (T) Protocol not supported!
[14:46:14 - 30/01/2024] (E) Could not fetch data from Horizons!
[14:46:14 - 30/01/2024] (T) Pulled 0 Horizons objects!
[14:46:14 - 30/01/2024] (T) Update pass trajectory...
[14:46:14 - 30/01/2024] (T) Pulling Horizons data...
[14:46:14 - 30/01/2024] (T) Protocol not supported!
[14:46:14 - 30/01/2024] (E) Could not fetch data from Horizons!
```

... my QTH entries in settings.json are:

```
    "satdump_general": {
        "qth_lat": {
            "value": 37.78
        },
        "qth_lon": {
            "value": -77.61
        },
        "qth_alt": {
            "value": 61.0
        },
        "default_qth_label": {
            "value": "K4KDR"
        },
```

Many thanks for any help!

-Scott,  K4KDR

**Comment by Aang23** [comment]
From what I see, you need to re-build libnng with mbedTLS support. Horizons only accepts https unfortunately...

**Comment by K4KDR** [comment]
I should add that I just noticed that there's a test available in the **nng** repository.   Here is the output from that:

```
k4kdr@3010i5:~/nng/build$ ./tests/tls
ok      ./tests/tls                                            2.230s
```

**Comment by Aang23** [comment]
Did you do cmake .. when building SatDump? Perhaps do a clean build to be sure?

**Comment by K4KDR** [comment]
My clean build of SatDump after installing / updating those other items included the steps:

(same steps that I've always followed to update to the latest version)     

** of course, of different (or additional) steps are better, I'm  happy to adjust!

```
cd ~/satdump
rm -rf build
git pull -v
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DPLUGIN_AIRSPYHF_SDR_SUPPORT=OFF -DPLUGIN_HACKRF_SDR_SUPPORT=OFF -DPLUGIN_LIMESDR_SDR_SUPPORT=OFF -DPLUGIN_PLUTOSDR_SDR_SUPPORT=OFF -DPLUGIN_BLADERF_SDR_SUPPORT=OFF -DPLUGIN_SDRPLAY_SDR_SUPPORT=OFF -DPLUGIN_MIRISDR_SDR_SUPPORT=OFF -DPLUGIN_SPYSERVER_SUPPORT=OFF -DCMAKE_INSTALL_PREFIX=/usr ..
make -j3
ln -s ../pipelines .
ln -s ../resources .
ln -s ../satdump_cfg.json .
```

**Comment by Aang23** [comment]
Which OS are you doing this on?

**Comment by K4KDR** [comment]
Ubuntu 18.04.

Interesting that the 'test' from the **nng** repository gives a positive response but apparently the same chain is somehow not being used on my system by SatDump

```
k4kdr@3010i5:~/nng/build$ ./tests/tls
ok      ./tests/tls                                            2.230s
```

**Comment by Aang23** [comment]
I will check on my end.

**Comment by Aang23** [comment]
@K4KDR is this still a problem?

**Comment by K4KDR** [comment]
Thanks for checking in!   Yes, unfortunately no change.  Clearly an issue on my end, but I don't have a clue even where to look.  I don't know what that functionality depends on.

![Screenshot from 2024-04-30 15-33-28](https://github.com/SatDump/SatDump/assets/19886368/0fa2a40e-f346-4c4b-944b-6dcaefc4d044)

**Comment by Aang23** [comment]
It's definitely NNG not supporting https here, the log says so... Perhaps try purging all traces of NNG and re-building?

**Comment by K4KDR** [comment]
Thanks so much!   Will work on that & report back.

**Comment by K4KDR** [comment]
After finding that 'sudo make uninstall' did not work from my /nng folder, I **searched my entire system for all instances to 'libnng' and deleted all files & folders found**.

Then, in the **/nng** folder I deleted the build folder and did a 'git pull -v' to be sure that I had the latest version.

The nng install steps were then followed:

```
cd nng
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr ..
make -j4
sudo make install
```

... and that was error-free.

Back in the **satdump** folder, I renamed the build folder, ran 'git pull -v' for the latest version, and built SatDump normally with no errors.

Unfortunately, when clicking on the '**Horizons**' button, I get the exact same result:

```
[15:17:38 - 02/05/2024] (T) Using QTH -77.610000 37.780000 Alt 61.000000
[15:17:38 - 02/05/2024] (T) Updating elements...
[15:17:38 - 02/05/2024] (T) Update pass trajectory...
[15:17:47 - 02/05/2024] (T) Pulling object list from Horizons...
[15:17:47 - 02/05/2024] (T) Protocol not supported!
[15:17:47 - 02/05/2024] (T) Pulling Horizons data...
[15:17:47 - 02/05/2024] (T) Protocol not supported!
[15:17:47 - 02/05/2024] (E) Could not fetch data from Horizons!
[15:17:47 - 02/05/2024] (T) Pulled 0 Horizons objects!
[15:17:47 - 02/05/2024] (T) Update pass trajectory...
[15:17:47 - 02/05/2024] (T) Pulling Horizons data...
[15:17:47 - 02/05/2024] (T) Protocol not supported!
[15:17:47 - 02/05/2024] (E) Could not fetch data from Horizons!
[15:17:47 - 02/05/2024] (T) Pulled 0 Horizons objects!
```

**Comment by K4KDR** [comment]
Thank you so much!!

Whatever was fixed in https://github.com/SatDump/SatDump/issues/728
... finally allows me to use the Horizons capability in SatDump.

![Screenshot from 2024-06-09 08-27-03](https://github.com/SatDump/SatDump/assets/19886368/afc502d8-1ae7-42fb-b411-40606a45a701)

... appreciate all you do for us!

-Scott
