### ISSUE TITLE
SDRconnect --server Connection

### ISSUE THREAD

**Issue by madjuju** [SatDump/SatDump#619]
**What would you want to be added to satdump?**
to be able tu connect to a SDRconnect server

**Describe the feature you'd like to have**
to be able tu connect to a SDRconnect server

**Describe alternatives you've considered**
Like RTL_TCP add to be able tu connect to a SDRconnect server

**Additional context**
Here you can for provide more information about what you'd like to see as the end result. Feel free to also post images if you have ideas regarding the UI

**Comment by Aang23** [comment]
I can look into it, but as the protocol and really everything is undocumented I can't make any guarantee.

In the meantime many other options will work to do the same thing.

**Comment by Aang23** [comment]
I have asked SDRPlay directly about this. It's not possible at the moment, and will only be later on when they will release later features. I'll therefore close this issue until this becomes viable to implement.
