### ISSUE TITLE
Build on rasberry pi "bookworm" fails (~since last week ?)

### ISSUE THREAD

**Issue by Glassnost** [SatDump/SatDump#622]
**Description of the issue**

**Hardware (SDR/PC/OS)**
Raspberry Pi 4, bookworm 12
 
**Version (Eg, 1.0.0, CI Build 171)**
SatDump > 1.1.4-7402e03a

Following instruction to build/compile @ https://github.com/SatDump/SatDump

**Logs after the crash** (satdump.log from ~/.config/satdump or %appdata%\satdump)

**Other info (Eg, Screenshots) / Files useful for debugging (CADU, etc)**
![image](https://github.com/SatDump/SatDump/assets/159002151/a36ef961-bfab-445a-8fec-289d1ae3b511)

![image](https://github.com/SatDump/SatDump/assets/159002151/ab3d8730-3cdd-4d69-b929-4d8fa14e7bb2)

[CMakeError.log](https://github.com/SatDump/SatDump/files/14169900/CMakeError.log)
[CMakeOutput.log](https://github.com/SatDump/SatDump/files/14169901/CMakeOutput.log)

Compiled/compiles well until SatDump > 1.1.4-7402e03a

Please just let me know in the case additional information might  be required.

Thanks a lot for your patience, all the time invested and the brilliant work you do here!

Regards
Karsten

**Comment by Aang23** [comment]
You need to have `jemalloc` installed.

`sudo apt install libjemalloc-dev`

**Comment by Glassnost** [comment]
Uncredible! Have already found that out on my own since and just wanted to report/add that.
Now your reply was faster.
Thanks a lot. 
Perhaps you / someone may be so kind to add that to the instructions pls. ?

Good and continued success, all the best and thanks again! :-)

**Comment by Aang23** [comment]
Actually this is already in the Debian instructions! - Though probably doesn't show without scrolling to the right.

Thanks & you're welcome!
