### ISSUE TITLE
nproc not a valid MacOS command (solution provided)

### ISSUE THREAD

**Issue by BjornB2** [SatDump/SatDump#629]
**Description of the issue**

Following the steps to compile satdump for mac myself, I ran into the issue that the nproc part of "make -j`nproc`" is not recognized. Further investigation learned that nproc is not a valid command on MacOS. 

On [this](https://github.com/memkind/memkind/issues/33) thread I found the solution: simply create an alias with 

`alias nproc="sysctl -n hw.logicalcpu"`

After that the command "make -j`nproc`" no longer gives an error and all compiles fine.

Maybe you can add this in the compile steps.

**Comment by JVital2013** [comment]
Great catch! We'll fix this
