### ISSUE TITLE
Support SDR Play- RSP1B

### ISSUE THREAD

**Issue by pa0alw** [SatDump/SatDump#642]
Hallo,
Should it possible to support in Satcom for the SDRplay RSP1 receiver in the near future?

Greetings

Walter

**Comment by Aang23** [comment]
Yes.

**Comment by pa0alw** [comment]
Thanks,
When i connect a RSP1B i get the message:
Device:Unknow RSP-2401017760
           This device is not supported yet,or perhaps a clone

**Comment by JVital2013** [comment]
Hi @pa0alw,

Can you try this again with the latest nightly? Some code was recently merged to support the RSP1B

**Comment by pa0alw** [comment]
Which version? I don't have a Linux computer,
I can test only the 1.1.4 windows version
Walter.

**Comment by JVital2013** [comment]
Nightly builds are available here: https://github.com/SatDump/SatDump/releases/tag/nightly

**Comment by pa0alw** [comment]
Thanks,
I install the latest Nightly version V1.2.0-324d226.
I see the correct device RSP1B 2401017760 in the recorder screen, started it but there is no reception and waterfall info.

Walter

**Comment by pa0alw** [comment]
With the latest Nightly version V1.2.0-ff6ca6 still no reception with the RSP1B in the waterfall/panadpter screen
You can see that the waterfall is running,

Walter.

**Comment by Aang23** [comment]
@pa0alw this should be fixed in Windows builds.
