### ISSUE TITLE
Question: How to get cadu frames out via TCP in real-time?

### ISSUE THREAD

**Issue by nils10** [SatDump/SatDump#650]
Hi,

First of all I would like to say that this is an impressive piece of software, great work!

I'd like to ask a question regarding satdumps TCP frame output. I've seen this on twitter https://twitter.com/HRPTEgor/status/1756631073566413230 and wanted to replicate this for example for some satellites like METOP and others. Any suggestions what I need to do to be able to pipe cadu frames out via TCP like that?

I've tried a few different things like passing in --server_address 0.0.0.0 --server_port 5004 cmd line arguments when starting satdump-ui.exe. Also tried copying the "xrit_goesrecv_publisher" work field into the sats json pipeline file. Both didnt result in any cadu frames to be outputted unfortunately so far.

Thanks for any feedback you may have!

**Comment by Aang23** [comment]
@nils10, what @Foxiks posted should answer this. I'll close for now.
