### ISSUE TITLE
satdump-ui daily build displaying 1.2.0-67e652c3 version

### ISSUE THREAD

**Issue by f6bvp** [SatDump/SatDump#651]
While SatDump SDR Server displays v1.1.4 

Starting SatDump v1.2.0-67e652c3

did I make something wrong ?

![Capture d’écran du 2024-03-01 14-46-29](https://github.com/SatDump/SatDump/assets/14106669/ca808b33-c840-4814-8e8d-c5cfeade2928)

Bernard

**Comment by JVital2013** [comment]
The version has been bumped to 1.2.0 due to core changes - if your SDR server still says 1.1.4, an old build is loading from somewhere. All new builds say 1.2.0, for the CLI, GUI, and SDR server.

**Comment by f6bvp** [comment]
Thanks for explanation.
