### ISSUE TITLE
Failed to start satdump after Win 11 install

### ISSUE THREAD

**Issue by f6bvp** [SatDump/SatDump#661]
Just started a new mini PC with Windows 11 that was unfortunatly in German that I do not understand.
"Nobody is perfect" !

Download and installed satdump for windows 64 was ok.

Click to start satdump fails with a window in german and I already explained ....

What is wrong ?

![Capture d'écran SatDump 2024-03-09 192707](https://github.com/SatDump/SatDump/assets/14106669/3370318c-2e39-41d4-93e7-a4747241f219)

**Comment by JVital2013** [comment]
I think we can let it slide that you don't know German ;). It looks like some of your system settings might be set to German now for some reason.

The problem at hand, though, is that it appears your Visual C++ Runtime got removed. You can re-install it from here: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by f6bvp** [comment]
Hello,
Thanks for very fast answer and excellent diagnostic. It works ! 
Satdump jumped on my screen.
You are fantastic !
Bernard
