### ISSUE TITLE
Stopping geostationary pipelines manually makes the app freeze and get marked as "not responding" by Android

### ISSUE THREAD

**Issue by Cpt-Dingus** [SatDump/SatDump#669]
**Description of the issue**
As the title says, after hitting `Stop` on pipelines, SatDump begins writing the images received from geostationary satellites. While it's writing them, the app freezes and is marked as unresponsive by android. This is not the case when the pipeline isn't manually stopped and writes images while receiving the next batch.

**Hardware (SDR/PC/OS)**
Samsung Galaxy Tab S7, Android 13

**Version (Eg, 1.0.0, CI Build 171)**
1.2.0, happens on all versions

**Logs after the crash (satdump.log from ~/.config/satdump or %appdata%\satdump)**
N/A

**Other info (Eg, Screenshots) / Files useful for debugging (CADU, etc)**
Happens with GVAR and S-VISSR broadcasts.

**Comment by alsldlflglhljlk** [comment]
Can confirm this is a problem on Windows as well. Especially problematic when there are several unfinished images.

**Comment by JVital2013** [comment]
This has been fixed. Thanks @Aang23!
