### ISSUE TITLE
Satdump won't start up anymore please help me.

### ISSUE THREAD

**Issue by Marconist** [SatDump/SatDump#676]
**Description of the issue**
SatDump, previously working well, no longer wants to start correctly.
Initially, SatDump seems to start up fine with the entrance window. 
![intree venster](https://github.com/SatDump/SatDump/assets/32016347/8d893e65-b4c4-4f96-a51d-c65242a17cc6)

But after loading the TLE, the installation stops and a black entrance window of Satdump v.1.4 appears.
![bug](https://github.com/SatDump/SatDump/assets/32016347/167a2748-34c3-434b-86ae-8a15069b120e)

What have I tried:
Restart PC:  negative, start SatDump
Satdup removed, restart PC, install Satdump:   negative.

The problem started when the following changes were made to the UserInterface, but I doubt this is the cause.
![userinterface](https://github.com/SatDump/SatDump/assets/32016347/77181890-8cf5-4edd-97a1-1fd324354fda)

**Hardware (SDR/PC/OS)**
Operation system: Windows 11

**Version (Eg, 1.0.0, CI Build 171)**

![wWindows](https://github.com/SatDump/SatDump/assets/32016347/4b19a426-2983-4d26-bbca-40f420b27f42)

Satdump v.1.1.4

**Logs after the crash** (satdump.log from ~/.config/satdump or %appdata%\satdump)
No Logs.

**Other info (Eg, Screenshots) / Files useful for debugging (CADU, etc)**
does not apply

**Comment by Aang23** [comment]
Perhaps try deleting the settings.json in `%appdata%\satdump` ?

**Comment by Marconist** [comment]
For me the only solution was to deeply uninstall Satdump. 
I had to set everything up again, but that didn't take much time. **Problem solved**
