### ISSUE TITLE
INSPIRE-SAT 7 wrong frequency in UVSQ.json

### ISSUE THREAD

**Issue by F1IPY** [SatDump/SatDump#680]
**Description of the issue**
INSPIRE-SAT 7 wrong frequency in UVSQ.json
should be 435.2e6 for the spino board and/ or 437.41e6 for the telemetry

**Hardware (SDR/PC/OS)**

**Version (Eg, 1.0.0, CI Build 171)**
SatDump V1.1.4

**Logs after the crash** (satdump.log from ~/.config/satdump or %appdata%\satdump)

**Other info (Eg, Screenshots) / Files useful for debugging (CADU, etc)**

**Comment by JVital2013** [comment]
Thanks for the report! The frequency for SPINO already looked to be correct, but I fixed the frequency for the TLM in the latest commit.
