### ISSUE TITLE
Overlay incorrect.

### ISSUE THREAD

**Issue by Galoosis** [SatDump/SatDump#690]
Although my location is correct the overlay and location for some passes of NOAA are wrong. I am in Washington state and it is showing the passes over Africa and the Antarctic. Images are saved upside down.

RSP1a/Ryzen 6 core/Windows10 pro desktop

Version v1.2.0-c899f09

![channel_4_projected](https://github.com/SatDump/SatDump
![channel_4_projected](https://github.com/SatDump/SatDump/assets/78892218/16252dac-2c2f-4544-94b7-2f538c55612d)
/assets/78892218/d8c2d251-15a1-4561-ab23-a2441a355e2e)
![channel_4_projected](https://github.com/SatDump/SatDump/assets/78892218/9bbfbccc-d2a0-411d-818f-11da895b5e9b)

![channel_4_projected](https://github.com/SatDump/SatDump/assets/78892218/f153e7db-24b7-442f-959c-e8147c09d735)

**Comment by Galoosis** [comment]
I now have it installed on 3 Windows10 pc's. Same issues on all 3. It crashes after a short amount of time requiring task manager to close it.

**Comment by Aang23** [comment]
Are the times in the viewer for the passes correct? And are TLEs up-to-date?

**Comment by JVital2013** [comment]
Also, make sure you have the right satellite selected here:

![image](https://github.com/SatDump/SatDump/assets/24253715/cd87b54f-f603-40fa-ac1b-5a1637c6d3e4)

**Comment by Galoosis** [comment]
> Are the times in the viewer for the passes correct? And are TLEs up-to-date?

Yes, the times are correct and the TLE's are up to date.

**Comment by Galoosis** [comment]
> Also, make sure you have the right satellite selected here:
> 
> ![image](https://private-user-images.githubusercontent.com/24253715/325020748-cd87b54f-f603-40fa-ac1b-5a1637c6d3e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MjcwMjQsIm5iZiI6MTcxMzkyNjcyNCwicGF0aCI6Ii8yNDI1MzcxNS8zMjUwMjA3NDgtY2Q4N2I1NGYtZjYwMy00MGZhLWFjMWItNWExNjM3YzZkM2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAyNDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMWI4Yzc4YmIxZjdiNWE1MGQwMzNkMTU5MjVkZmNkMGQyZDZjODYyODg3NjVkMGVmMTdjMmQ0Y2RkM2RkOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DPFghtCV8aftu0vkXX8LBMYJ9MpMbMUHsQfHH5ldpdU)

This I did not have set correctly. Thanks for this info. I did figure out why it was crashing I think. I updated the SDRplay API. It has been running for a little over 24 hours.

**Comment by JVital2013** [comment]
Ah yes, the SDRplay API... we've had many headaches with this. Is it still OK after updating, several days later?

**Comment by Galoosis** [comment]
Yes, it is still running. The overlay issue is also good now. The NOAA images are saved upside down which is not a big issue. It would be neat if the settings were saved when the program is closed. Some of us would love for it to automatically run using the last settings when opened. Thanks for your help.

**Comment by JVital2013** [comment]
Are the upside down ones night passes? If so, this is "normal" - at least for now. This is because the images are saved in the same orientation "as the satellite sees it", and at night POES satellites go south to north. We've had requests before to re-orient the passes automatically, but that has a lot of internal implications to consider.

To make it automatically start autotrack when launching SatDump UI, you should be able to modify the shortcut and add...

```
--start_autotrack --start_recorder_device`
```

...to auto-start the SDR and tracking.

![438221894_7785758358143392_4023521064561815775_n](https://github.com/SatDump/SatDump/assets/24253715/0651e0d6-39fc-4397-bd89-334cd4769cc0)
