### ISSUE TITLE
Map overlay issue at high latitudes

### ISSUE THREAD

**Issue by N1TX** [SatDump/SatDump#694]
Live and offline processing generated maps show my correct location (65N 147W) in Alaska. Alaska is shown correctly, but the processor also adds what appears to be European boundaries, cities, etc. The result is a jumbled mess. Example from NOAA-15 today. Impacts all NOAA APT as well as METEOR LRPT.

![avhrr_3_APT_channel_A_map](https://github.com/SatDump/SatDump/assets/167711155/c197feea-c9b9-4a97-ae98-44aaa99adf29)

RX: RSPduo and Nooelec XTR
PC: 
Processor	Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz   4.00 GHz
Installed RAM	16.0 GB (15.9 GB usable)
Device ID	62332575-13A0-4595-9AE8-DC119E84FEF5
Product ID	00330-80000-00000-AA948
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Pro
Version	22H2
Installed on	‎10/‎30/‎2020
OS build	19045.4291
Experience	Windows Feature Experience Pack 1000.19056.1000.0

**Comment by Aang23** [comment]
I have pushed a fix for this in the current system. I'll re-visit this soon when re-working the internals of projections, but it'll be fine for 99% of cases now.
