### ISSUE TITLE
SDRplay RSP1A CLI command.

### ISSUE THREAD

**Issue by ve3elb** [SatDump/SatDump#711]
@JVital2013 

Am trying to add the SDRplay RSP1A to CLI command but not connecting to the SDR device it keeps crashing. No issues working in GUI mode.  

--source sdrplay
--source rsp1a
--source sdrplay_rsp1a
--source sdrplay rsp1a
--source sdrplayrsp1a 

All combinations and nothing works. Any ideas please. Looking for the correct source command for sdrplay devices. 

Thank You.

**Comment by JVital2013** [comment]
It should be `--source sdrplay`. What error are you getting when you try it?

**Comment by ve3elb** [comment]
@JVital2013 

Thank you for the reply but once it gets to the point "opening SDRplay device" it shuts down. 

I found the issue. Wrong Samplerate can't be 2.4. It's 2.0 or 3.0. 

Thank you.
