### ISSUE TITLE
Windows version 1.1.4 crash a startup

### ISSUE THREAD

**Issue by f6bvp** [SatDump/SatDump#712]
Immediate crash of satdump v1.1.4 while tentative connexion to remote site.
![Capture d'écran 2024-03-09 191530](https://github.com/SatDump/SatDump/assets/14106669/9e08d6fd-cf8c-4d8a-8987-b7f2eb9d26fe)

After uninstalling and reinstalling I get same crash.
Should I delete some file or directory ? 

Regards,

Bernard

**Comment by f6bvp** [comment]
![Capture d'écran 2024-05-10 204131](https://github.com/SatDump/SatDump/assets/14106669/1a0a50ad-f9ca-4fb8-be65-141f8e18e06e)

**Comment by f6bvp** [comment]
Crash immediate

**Comment by JVital2013** [comment]
Hello again!

Are you mixing and matching versions between client and server? Due to a change the 1.1.4 client is not compatible with the latest 1.2.0 nightly server.

We should probably fix the crash, though. @RAD750 also had this issue

**Comment by f6bvp** [comment]
I understand. No problem. I can run Linux too.
Thank you
Bernard

**Comment by f6bvp** [comment]
Closed as Windows Satdump 1.2.0 version is starting and doing very nicely.
Thanks a lot !

Bernard
