### ISSUE TITLE
Overriding the default configuration

### ISSUE THREAD

**Issue by matveyhim** [SatDump/SatDump#721]
**Description of the issue**
I wanted to disable the MCIR autogen and add some projections, but changing satdump_cfg and settings.json does not work.
**Hardware (SDR/PC/OS)**
Ubuntu 22.04
**Version (Eg, 1.0.0, CI Build 171)**
SatDump v1.2.1-59380c0c
**Logs after the crash** (satdump.log from ~/.config/satdump or %appdata%\satdump)

**Other info (Eg, Screenshots) / Files useful for debugging (CADU, etc)**
viewer array in settings.json file
```
"viewer": {
        "instruments": {
            "avhrr_3": {
                "MCIR (Uncalibrated)": {
                    "autogen": false
                },
                "APT channel A": {
                    "draw_map_overlay": true,
                    "project": {
                        "width": 4096,
                        "height": 2048,
                        "draw_map_overlay": true,
                        "config": {
                            "type": "stereo",
                            "lat":60,
                            "lon": 77,
                            "scale": 1000
                        }
                    }
                }
            }
        },
```

**Comment by matveyhim** [comment]
No, it doesn't look like it. If I miss any `}` character in the files, satdump will crash. Or if I add the msu_mr section in settings.json, it will be sorted to the end of the instruments section

**Comment by matveyhim** [comment]
Strangely, the projection does not work with bad images, but it works with good ones that I received today.

**Comment by Aang23** [comment]
Are you receiving APT or HRPT? If using APT all images good or bad should project. If it's HRPT very low signal levels can how problems and there's nothing to do about it.

**Comment by matveyhim** [comment]
It APT. And I had another bug on windows - the map overlay that I do in the viewer was strange, but the projections are normal

**Comment by matveyhim** [comment]
It's APT. I also have a bug in Windows - the map overlay that I'm doing in the Viewer is getting weird, but the projections remain normal. Everything is fine in ubuntu too. There's nothing wrong with the names of the satellites I selected.

**Comment by JVital2013** [comment]
If you are still having an issue about projection or map overlays, please open another issue to keep things tidy. Having multiple issues in a single ticket causes confusion.

As for your original issue (overriding the default configuration), please try again with the latest build. "Advanced mode" has been implemented, which lets you do this from the GUI. Behind-the-scenes, advanced mode works the same way you were trying to override the settings.

If you are still having issues with overriding the config, please post:
- Your entire satdump_cfg.json, and the path you copied it from
- Your entire settings.json, and the path you copied it from
- The entire log file from an instance where your custom settings were not applying

**Comment by JVital2013** [comment]
@matveyhim are you still having issues overriding the default configuration?

**Comment by matveyhim** [comment]
I tested it today, turned off the projection of ch4 from the advanced settings, everything worked properly

**Comment by JVital2013** [comment]
Great, glad to hear it!
