### ISSUE TITLE
Noaa missing Image

### ISSUE THREAD

**Issue by Stepman55** [SatDump/SatDump#726]
V 1.2.1-3e07abe - Win11
Noaa APT Image 'Products', RGBComposites/Mcir Rain (uncal.), Only shows the color Layer but without the satellite picture belonging.

**Comment by Stepman55** [comment]
a few pictures and the corresponding log
![Screenshot 2024-06-09 133019](https://github.com/SatDump/SatDump/assets/171611213/e52599ce-c775-47e3-9771-84d5d3e532b1)
![Screenshot 2024-06-09 133048](https://github.com/SatDump/SatDump/assets/171611213/f317c1e3-2410-414f-9298-58209304d22b)
[satdump-20240609T132737.log](https://github.com/user-attachments/files/15751652/satdump-20240609T132737.log)

**Comment by Stepman55** [comment]
Recording live or loading makes no difference.
The data comes from the still functioning version 1.2.0-1e40ef1. However, the log is no longer available there.

**Comment by JVital2013** [comment]
Is this still happening to you? If so, could you please share an example dataset? (Zip up the entire output folder for a single pass that SatDump generates, and upload it here)

**Comment by Stepman55** [comment]
Yes
here is the result.
You can easily produce it yourself. Simply receive a short APT noise image manually. Go to the viewer, select MCIR Rain and now you will see it, ...not.
All other channels show the noise image.
[2024-08-01_06-47_noaa_apt_137.62 MHz.zip](https://github.com/user-attachments/files/16451834/2024-08-01_06-47_noaa_apt_137.62.MHz.zip)
[satdump-20240731T215242.log](https://github.com/user-attachments/files/16451851/satdump-20240731T215242.log)

**Comment by alsldlflglhljlk** [comment]
I do believe that MCIR rain strips clouds from the image and places them on an internal map. Because your image isn't really a real image, it does nothing.

**Comment by JVital2013** [comment]
Ah, I see what the issue is. The bug happened for you, and not me, because it only happens if the product image format is set to jpeg in settings.

I'll push a fix in a moment; you can expect a working nightly in ~30 mins!

![image](https://github.com/user-attachments/assets/d89a0739-62bf-41b0-bcf0-5730e14b26d1)
