### ISSUE TITLE
MetOp NOSYNC

### ISSUE THREAD

**Issue by ArgoNavi** [SatDump/SatDump#727]
I'm having an issue with MetOp not achieving sync when using autotrack despite having plenty of SNR, If I stop/restart autotrack during the pass it immediately achieves sync and starts decoding.

before restart:
[satdump-20240607T171805.log](https://github.com/user-attachments/files/15746383/satdump-20240607T171805.log)

after restart:
[satdump-20240607T231535.log](https://github.com/user-attachments/files/15746384/satdump-20240607T231535.log)

**Comment by Aang23** [comment]
Can you show a screenshot?

**Comment by ArgoNavi** [comment]
I’ll take one during the next pass.

**Comment by ArgoNavi** [comment]
before restarting the decoder:
<img width="1348" alt="Screenshot 2024-06-08 at 10 54 21 PM" src="https://github.com/SatDump/SatDump/assets/63644530/fecedfd3-a61a-4ee2-a01b-8892caaa0ffd">

after restarting:
<img width="1392" alt="Screenshot 2024-06-08 at 10 55 03 PM" src="https://github.com/SatDump/SatDump/assets/63644530/9d2d4088-fc2a-447d-b0a1-3adf7bcb5d28">

**Comment by Aang23** [comment]
Are you using a RTL-SDR by any chance? If so, some problems are not unexpected with the default values as it's on the edge. If this is the case I can tell you what to change to improve things.

**Comment by ArgoNavi** [comment]
Yes I'm using an RTL-SDR Blog V4, what settings should I change?

**Comment by ArgoNavi** [comment]
Solved by increasing my sample rate to 2.88 and enabling both dc block and agc.

![avhrr_3_composite](https://github.com/SatDump/SatDump/assets/63644530/6df547af-82d8-4005-b34d-403347c4d95b)
