### ISSUE TITLE
SPS is invalid，FY3C-AHRPT

### ISSUE THREAD

**Issue by ZeshengKang** [SatDump/SatDump#729]
Error (3)
SPS is invalid. Must be above 1! =>
D:\a\SatDump\SatDump\src-core\modulesidemod\module_demod_base.cpp:93
Friends, what is the problem? Where can I search for the SPS of FY3C?
![747992eb9e6770990f771499bd64921](https://github.com/SatDump/SatDump/assets/172378878/6372a43a-3a6d-47d9-8785-71163042fe2b)
![0194b117ccb20ce583cfa2224fc6e95](https://github.com/SatDump/SatDump/assets/172378878/15de983a-847b-4801-b539-4c33d91b9a83)

**Comment by ZeshengKang** [comment]
> 您使用的是哪种特别提款权？您需要更多带宽。

Thank you. After using 2.88M, it returned to normal

**Comment by Aang23** [comment]
2.88m on the RTL is not usually stable however. You might need a better SDR.
