### ISSUE TITLE
Installation - Raspberry Pi 4

### ISSUE THREAD

**Issue by DYT-Flyer** [SatDump/SatDump#734]
Hi,

I have a Raspberry Pi 4 B which requires some dependencies not stated in the installation guide - specifically BladeRF, AAudio, RFNM, RDLPlay, and some others. I didn't know if there is an assumption that these are supposed to be already installed or installed in some manner besides common package managers (possibly PyBombs?). And if there is an easier way to install these.

Thanks

**Comment by K4KDR** [comment]
Don't know if this is helpful - or even recommended, but **it's what I do** to not be bothered with dependencies for products that I do not own.

My CMAKE command when building SatDump is:

`cmake -DCMAKE_BUILD_TYPE=Release -DPLUGIN_AIRSPYHF_SDR_SUPPORT=OFF -DPLUGIN_HACKRF_SDR_SUPPORT=OFF -DPLUGIN_LIMESDR_SDR_SUPPORT=OFF -DPLUGIN_PLUTOSDR_SDR_SUPPORT=OFF -DPLUGIN_BLADERF_SDR_SUPPORT=OFF -DPLUGIN_SDRPLAY_SDR_SUPPORT=OFF -DPLUGIN_MIRISDR_SDR_SUPPORT=OFF -DPLUGIN_SPYSERVER_SUPPORT=OFF -DCMAKE_INSTALL_PREFIX=/usr ..`

**Comment by JVital2013** [comment]
Hello @DYT-Flyer!

All of those dependencies you list are not required, unless you have specific need for them. All of these things are "niche"/not applicable, and you can ignore the messages in the build log that they are not found. Cmake is still completing successfully (unless it is not, in which case, please share the entire output of cmake).

Unless, of course, you have a bladeRF, RFNM, etc and are looking for help with that?
