### ISSUE TITLE
Dots in demodulator constellation window are out of bounds

### ISSUE THREAD

**Issue by dvdesolve** [SatDump/SatDump#738]
**Description of the issue**
I've noticed for APT and LRPT modes that some dots are out of black box boundaries in the constellation window (see screenshot below)
![Screenshot from 2024-06-28 14-23-55](https://github.com/SatDump/SatDump/assets/32072485/97170630-1597-4a84-9341-4122500c2f95)

**Hardware (SDR/PC/OS)**
RTL-SDR blog v3 dongle
Arch Linux x86_64 rolling

**Version (Eg, 1.0.0, CI Build 171)**
latest git version

**Comment by alsldlflglhljlk** [comment]
Sure, but is this really a bug? It doesn't impair SatDump's ability to decode and demodulate satellite signals.

**Comment by dvdesolve** [comment]
of course, that's not a fatal bug. I've just chosen one out of three templates during posting the issue

**Comment by JVital2013** [comment]
It's still a bug in my book - fixed as of the latest nightly! Thanks for the poke to finally fix this
