### ISSUE TITLE
Incorrect percentage/progress calculations for APT and LRPT modes

### ISSUE THREAD

**Issue by dvdesolve** [SatDump/SatDump#739]
**Description of the issue**
I've noticed that for APT and LRPT modes progress calculator sometimes gives `NaN`s or `inf`s (see screenshot below)
![Screenshot from 2024-06-28 14-23-55](https://github.com/SatDump/SatDump/assets/32072485/de2aff45-c304-47ad-9067-e3fb88822278)

**Hardware (SDR/PC/OS)**
RTL-SDR blog v3 dongle
Arch Linux x86_64 rolling

**Version (Eg, 1.0.0, CI Build 171)**
latest git version

**Comment by JVital2013** [comment]
Duplicate of #202
