### ISSUE TITLE
DC Carrier on empty baseband

### ISSUE THREAD

**Issue by alsldlflglhljlk** [SatDump/SatDump#740]
**Description of the issue**

Attached to this issue is a baseband recording only containing noise (file extension changed to `.webm` to allow upload). In SDR++, the file plays as expected, but SatDump adds a spurious DC carrier in the center of the FFT.

[recording.webm](https://github.com/SatDump/SatDump/assets/119443367/579095c3-96c4-4d50-a385-44e681ccba24)

**Hardware (SDR/PC/OS)**

Intel Core i3-4000M@2.40 GHz

Windows 10 22H2

**Version (Eg, 1.0.0, CI Build 171)**

v1.2.0

**Logs after the crash** (satdump.log from ~/.config/satdump or %appdata%\satdump)

N / A

**Other info (Eg, Screenshots) / Files useful for debugging (CADU, etc)**

Playing through SDR++:
![image](https://github.com/SatDump/SatDump/assets/119443367/3c4a78fb-4a30-49e7-8cb5-c3ce09cc610e)

Playing through SatDump:
![image](https://github.com/SatDump/SatDump/assets/119443367/66e8ae82-12bb-4df0-82e3-31a68bbce6e7)

**Comment by JVital2013** [comment]
The spike is in the baseband; it's visible in SDR++ if you turn IQ correction off

![image](https://github.com/SatDump/SatDump/assets/24253715/ecd76e6a-414f-4105-962c-08d35fd8cc27)

**Comment by alsldlflglhljlk** [comment]
Is there such an IQ correction option in SatDump? I've tried turning on the "DC Blocking" switch in the demodulation options, but that doesn't seem to remove the spike in the FFT.

**Comment by alsldlflglhljlk** [comment]
Alright, good to know. Thanks!
