### ISSUE TITLE
change "cd satdump" to "cd SatDump" in readme - installing on linux

### ISSUE THREAD

**Issue by JimmyeJones** [SatDump/SatDump#767]
**Description of the issue**
git clones satdump into a "SatDump" folder. to move the the next install step, you need to cd into "SatDump", not "satdump".

**Hardware (SDR/PC/OS)**
not needed

**Version**
NA

**Logs after the crash** (satdump.log from ~/.config/satdump or %appdata%\satdump)
NA

**Other info (Eg, Screenshots) / Files useful for debugging (CADU, etc)**
None

**Comment by ve3elb** [comment]
Yes that's a typo I had to fix it when installing.

**Comment by JVital2013** [comment]
Oops, I updated one place in the readme, but not another. Will fix in a sec.
