### ISSUE TITLE
DC blocking with sceduler

### ISSUE THREAD

**Issue by steppenwolf2000** [SatDump/SatDump#781]
When I use the scheduler in SatDump 1.2.0 it unchecks the DC blocking (which I checked before) when it starts to receive a satellite. I'm using a HackRF at the momernt so the recording is useless. 
I think it's not a great issue, but it would help if it is solved.
Thank's a lot !

**Comment by JVital2013** [comment]
Have you configured DC blocking in the scheduler config? The scheduler config overrides all settings done directly in the processing tab when not in multi-mode, by design.

![image](https://github.com/user-attachments/assets/3d04bba0-b640-4dea-8410-94021cadfe1b)

**Comment by steppenwolf2000** [comment]
Thank you for the advise, that's the solution!
