### ISSUE TITLE
tracking scheduler CLI

### ISSUE THREAD

**Issue by brightkill** [SatDump/SatDump#785]
Nice CLI update by Satdump, but I want to ask:
Is it possible to use tracking scheduler with CLI only (e.g. use it with Raspberry Pi via SSH)? If not, will it be implemented in future versions?

**Comment by JVital2013** [comment]
Yes, autotrack can be used via the CLI. For now, you need to manually compose a .json file to tell it what to track, but soon a feature will be added to export CLI autotrack configurations from the UI.

You can read up on configuring the json manually at https://www.a-centauri.com/articoli/automating-satellite-reception-with-satdump-cli.

**Comment by brightkill** [comment]
appreciate your post too much, big thanks

**Comment by JVital2013** [comment]
The ability to export cli autotrack configs from the UI is now available in the latest nightlies, and the soon-to-be released SatDump 1.2.1

![image](https://github.com/user-attachments/assets/26898dbd-aa3f-42b5-b376-35dd953184a3)
