### ISSUE TITLE
PlutoSDR: duplicate text in URI causing error

### ISSUE THREAD

**Issue by KentuckyFriedData** [SatDump/SatDump#788]
**Description of the issue**
duplicate "usb:" backend causing error when using usb mode, but removing it from https://github.com/SatDump/SatDump/blob/master/plugins/sdr_sources/plutosdr_sdr_support/plutosdr_sdr.cpp#L180 appears to fix it for me on both machines :)

![Screenshot_20240821_105845](https://github.com/user-attachments/assets/2d5fbb6f-c851-4525-b6ba-d5d0d9ee3222)

**Hardware (SDR/PC/OS)**
SDR: PlutoSDR
PC/OS: Windows 10 (x64), Arch Linux (aarch64)

**Version (Eg, 1.0.0, CI Build 171)**
Windows (CI Build #1914)
Linux (built locally with commit [4f7ee7eeb394beaf341e08aff180ae733ffd02d6](https://github.com/SatDump/SatDump/commit/4f7ee7eeb394beaf341e08aff180ae733ffd02d6))

**Logs after the crash** (satdump.log from ~/.config/satdump or %appdata%\satdump)
N/A

**Other info (Eg, Screenshots) / Files useful for debugging (CADU, etc)**

**Comment by JVital2013** [comment]
The fix looks good to us; thanks!
