### ISSUE TITLE
Is it normal that SatDump crashes after processing a wav file ?

### ISSUE THREAD

**Issue by MoutonBinoclard** [SatDump/SatDump#795]
I tried this tutorial to see the Noaa satellite picture  : https://www.a-centauri.com/articoli/noaa-poes-satellites-reception
however, when I click start, after processing the audio, the software just closes itself. Is it normal ?

**Comment by zulufoxtrot** [comment]
I have the same issue.
Satdump 1.2.0 on macOS.
Satdump does process the file and does save it to the output directory.

**Comment by zulufoxtrot** [comment]
Satdump also throws an error at startup: "Failed to load TLEs"
<img width="728" alt="Screenshot 2024-08-31 at 12 06 53" src="https://github.com/user-attachments/assets/080ef949-a56d-49db-9c41-d47ad06ecd9f">
And the "tracking" window is blank:
<img width="365" alt="Screenshot 2024-08-31 at 12 07 24" src="https://github.com/user-attachments/assets/5da73f7d-f42c-41ea-a1f5-0f56eacffa15">

**Comment by JVital2013** [comment]
Hello everyone! No, crashing is not normal. We aren't the Windows Vista developers.

I'd recommend updating to the latest nightly (https://github.com/SatDump/SatDump/releases/tag/nightly) to see if that fixes it. If not, please share the log file from one of your crashes.

Thanks!

**Comment by brandondowns93** [comment]
Hi all,

I was running into this same problem (on macOS 11.7.10, also processing a .WAV), and after installing the nightly build per @JVital2013's recommendation, I'm no longer getting a crash. Thanks!

I'm attaching a log of when 1.2.0 crashed last, if that's of any help?
[satdump-20241017T211853.log](https://github.com/user-attachments/files/17441863/satdump-20241017T211853.log)

**Comment by zulufoxtrot** [comment]
Can confirm it no longer crashes on the nightly.

**Comment by JVital2013** [comment]
Thanks for the reports guys - it sounds like this one is fixed so I'll close it for now. If it re-surfaces, feel free to open a new issue.
