### ISSUE TITLE
GUI更新TLEs出问题

### ISSUE THREAD

**Issue by ZHENG0119** [SatDump/SatDump#798]
![屏幕截图 2024-09-03 200602](https://github.com/user-attachments/assets/dddec4fa-fd96-4294-8ffa-4c9cd3f5529f)
![屏幕截图 2024-09-03 2021222](https://github.com/user-attachments/assets/e8068aa9-6a25-420a-9447-6facf3e63c33)

**Comment by JVital2013** [comment]
This bug has been fixed in the latest nightly version - https://github.com/SatDump/SatDump/releases/tag/nightly
