### ISSUE TITLE
TLE Download

### ISSUE THREAD

**Issue by fpiering** [SatDump/SatDump#804]
**New User. Load installer for Windows, Install. Get Error message "Error updating TLE's. Not Updated"

**Windows 10. Version 22H2HP Envy Portable. Also tried on desktop, dame error.

**Version Satdump v1.2.0

**Logs after the crash** (satdump.log from ~/.config/satdump or %appdata%\satdump)

**see attached
![Hardware and software OS](https://github.com/user-attachments/assets/1be0624b-2854-4d5f-bb82-2aba9ccac128)
![TLE Error 2](https://github.com/user-attachments/assets/f4446e32-4ca8-4caa-a3ee-5e610c9c0a21)
![TLE Load Error](https://github.com/user-attachments/assets/0eb445f0-23f7-4aa9-a2ec-b7bb57283003)

**Comment by Aang23** [comment]
This has been fixed in nightly builds - and we should really do a release with that fix...
