### ISSUE TITLE
Problems with tle's

### ISSUE THREAD

**Issue by wds657** [SatDump/SatDump#811]
I'm having problems updating the TLE, has anyone else had this problem with the portable satdump? What should I change?
![Captura de pantalla 2024-09-19 181154](https://github.com/user-attachments/assets/95ef1ad0-691a-40b7-aaec-e5979b72f0f5)

**Comment by JVital2013** [comment]
This bug has been fixed in the latest nightlies: https://github.com/SatDump/SatDump/releases/tag/nightly
