### ISSUE TITLE
SatDump (nightly) stops responding on launch

### ISSUE THREAD

**Issue by jcv09** [SatDump/SatDump#817]
**Description of the issue**
When launching SatDump, the app stops responding after '0 TLEs loaded' message.

**Hardware (SDR/PC/OS)**
2023 Dell XPS 15, i7 rtx 4070, windows 11

**Version (Eg, 1.0.0, CI Build 171)**
Nightly

**Logs after the crash** (satdump.log from ~/.config/satdump or %appdata%\satdump)
[satdump-20240922T115331.log](https://github.com/user-attachments/files/17091067/satdump-20240922T115331.log)

**Comment by JVital2013** [comment]
Try removing the DLL located at C:\Program Files\SatDump\lib\satdump\plugins\remote_sdr_support.dll, and see if that fixes the issue for you

**Comment by jcv09** [comment]
There don't seem to be any files with that name there, could they have installed somewhere else?

**Comment by JVital2013** [comment]
According to the log file you uploaded, the file is there:

![image](https://github.com/user-attachments/assets/4a1a327b-1220-4aad-9b40-c7aeb7655411)

**Comment by jcv09** [comment]
My bad, I was looking for it in C:\Program Files\SatDump\plugins instead of C:\Program Files\SatDump\lib\plugins. It launches now, thank you!
