### ISSUE TITLE
Error on Nightly Build

### ISSUE THREAD

**Issue by waleed1668** [SatDump/SatDump#829]
**In offline processing get this message (Unknown EUMETSAT file type! FCI-1C-RRAD-HRFI-FD)**

**PC**

**Version (1.2.1)**
![IMG_8123](https://github.com/user-attachments/assets/a4746664-1cfc-4f89-9d5d-8c44c994a5e0)

**Comment by JVital2013** [comment]
Hello @waleed1668!

Support for HRFI (High Resolution) archives has been fixed in the latest nightly. It will be ready in about 20 minutes. Let us know if you have any other issues!

**Comment by waleed1668** [comment]
> Hello @waleed1668!
> 
> 
> 
> Support for HRFI (High Resolution) archives has been fixed in the latest nightly. It will be ready in about 20 minutes. Let us know if you have any other issues!

**Yes, it's working**
Thank you
