### ISSUE TITLE
FFT range (Waterfall/Spectrum) does not fit for Airspy HF+ Discovery - outside of display

### ISSUE THREAD

**Issue by db2os** [SatDump/SatDump#843]
No Spectrum/Waterfall with Airspy HF+ Discovery SDR because FFT Min setting is out of range (-150 limit).

- Hardware (AirspyHF, Win11 64 bit)
- latest nightly

below some screenshots in comparison with SDR++,  not that the Minimum slider is at maximum too.

![SatDump 2024-10-26 133403](https://github.com/user-attachments/assets/a22b6b8a-9817-41a8-9fd4-6a8d7f04c1a8)
![SDRpp 2024-10-26 133227](https://github.com/user-attachments/assets/130bc09f-e351-4307-b07c-f647e465430d)

**Comment by JVital2013** [comment]
Yes, this is something we need to address. For now, you can set the FFT min to a number lower than -150 by Ctrl+Clicking on the FFT Min slider, and typing a lower number (such as -180)

**Comment by db2os** [comment]
> Yes, this is something we need to address. For now, you can set the FFT min to a number lower than -150 by Ctrl+Clicking on the FFT Min slider, and typing a lower number (such as -180)

Oh,  that's a trick I did'nt know!!  Works nice..   Thanks for the hint!

**Comment by JVital2013** [comment]
Hey @db2os, what would be a good minimum value for use with the Airspy HF+ Discovery? How low should we go?

**Comment by db2os** [comment]
I think -160 should be fine

**Comment by JVital2013** [comment]
I'll just set that as a new minimum. We had talked about making the FFT range more dynamic, but this should suffice for now.
