### ISSUE TITLE
Autotrack focuses on one satellite

### ISSUE THREAD

**Issue by super-15** [SatDump/SatDump#844]
**Description of the issue**
After recieving one satellite using autotrack, it will wait to recieve the next pass of that satellite, not go to the next, nearest satellite.
**Hardware (SDR/PC/OS)**
SDRPlay RSPdx, Windows 10 freshly installed
**Version (Eg, 1.0.0, CI Build 171)**
Latest nightly build as of 10/26/2024

**Comment by JVital2013** [comment]
Could you please share a log and your `config.json` of this happening? I am unable top reproduce this problem - it always switches to the next satellite at its AOS

**Comment by JC167shearer** [comment]
I have this issue, too:

Actively tracking:

![image](https://github.com/user-attachments/assets/8a79ce06-e0c7-4b22-9e3a-2aa08666de74)
![image](https://github.com/user-attachments/assets/efef5be5-b321-4bee-8f67-b803ba6c621b)

After that pass, scheduler shows NOAA15 next, but Object Tracker still focused on Meteor M2-4:

![image](https://github.com/user-attachments/assets/1eeb3fe8-99ca-4d6c-ae5f-976472a7bd08)
![image](https://github.com/user-attachments/assets/5f093543-51d7-47d9-8596-168ba2a320be)

Will get json and logs this evening if the OP doesn't get it first. Thank you!

**Comment by JVital2013** [comment]
Thanks for the additional report. To clarify: does it actually start the processing for the correct satellite at AOS, and only the web interface is wrong? So far that looks like it might be the actual issue - the web interface is switching, but the tracking itself may still be OK

**Comment by super-15** [comment]
Yes, it seems only an issue with the UI. It switches at AOS.

**Comment by JC167shearer** [comment]
Correct. The UI stays "focused" (for lack of a better term) on the sat it just completed rather than shifting focus to the next sat on the scheduler.

**Comment by JVital2013** [comment]
OK - we will troubleshoot. Thanks all!

**Comment by JVital2013** [comment]
This should now be fixed in the latest nightly build. Let us know if you still have issues!
