### ISSUE TITLE
AWS No Images

### ISSUE THREAD

**Issue by ArgoNavi** [SatDump/SatDump#854]
I'm receiving a strong signal and getting "SYNCED" but no images are produced, system is running the latest nightly with AWS fixes.

[Log.txt](https://github.com/user-attachments/files/17611141/Log.txt)

<img width="975" alt="Screenshot 2024-11-03 at 11 01 31 AM" src="https://github.com/user-attachments/assets/a8eefd13-6a59-4f13-a591-4803020b3ad0">

![Screenshot 2024-11-03 at 11-01-01 SatDump Status Page](https://github.com/user-attachments/assets/236a5604-96c3-4d37-ab7f-11276aea0798)

**Comment by JVital2013** [comment]
AWS is only transmitting filler right now over most of the world. I just verified this myself 15 minutes ago. 

It seems that they are often doing data dumps over Europe at the moment, but that leaves the rest of us out in the cold.

Hopefully they start broadcasting actual data globally again soon!
