### ISSUE TITLE
Could not open RTL-SDR device!

### ISSUE THREAD

**Issue by heliumn55** [SatDump/SatDump#856]
Hello, 

using last release with windows 11 24H2, with an original  RTL-SRD.COM V4.
 Satdump works well with my sdrplay rspduo.

but with V4 nothing.
it says :  Could not open RTL-SDR device!   look picture below

![Capture d'écran 2024-11-05 191109](https://github.com/user-attachments/assets/561d8b89-4c51-42c1-8f14-e2d2cd4bb6f7)

very good work for that freeware

**Comment by JVital2013** [comment]
Based on the screenshot, you have not installed the driver correctly with Zadig (OEM #0 is the tell-tale sign here). Make sure you've properly installed the RTL-SDR driver with Zadig and try again.

These instructions still appear to be valid: https://www.rtl-sdr.com/getting-the-rtl-sdr-to-work-on-windows-10/

**Comment by heliumn55** [comment]
My V4 is already configured with Zadig for SDRSHARP!
it works very well

**Comment by heliumn55** [comment]
Ok You're right.
reinstall drivers again with zadig 2.9.
now it works

Thank you
