### ISSUE TITLE
SDRPlay RSP1B

### ISSUE THREAD

**Issue by AlanB-KG9PN** [SatDump/SatDump#873]
I just got a SDRplay RSP1B today. SatDump will not recognize it in Ubuntu. I have tried installing the .deb file and building from source. There simply is no option for SDRplay at all. I have installed the API, and all my SDR software other than SatDump sees it and it works fine. Any ideas as to what im doing wrong or what the fix is? (BTW the device is recognized and works fine under Windows on the same PC.)

**Comment by JVital2013** [comment]
Good evening! Can you please post the full log of SatDump opening so we can troubleshoot?

**Comment by AlanB-KG9PN** [comment]
I’m fairly new to Ubuntu, how would I find the log?
Sent from my iPad

On Nov 22, 2024, at 8:34 PM, Jamie Vital ***@***.***> wrote:

﻿

Good evening! Can you please post the full log of SatDump opening so we can troubleshoot?

**Comment by JVital2013** [comment]
The log is at ~/.config/satdump (.config is a hidden folder)

**Comment by AlanB-KG9PN** [comment]
I appreciate your help. I already figured it out. It was a problem with the API installation. I redid it and all is fine now!
Sent from my iPhone

On Nov 23, 2024, at 9:57 PM, Jamie Vital ***@***.***> wrote:

﻿

The log is at ~/.config/satdump (.config is a hidden folder)

**Comment by AlanB-KG9PN** [comment]
Thanks all for the help I figured it out. The first API install didnt go in correctly. It was my error.
